/**
 * @brief Register definitions for ADC peripherals
 */

#pragma once

#include "registers/register_helpers.h"


// ADC Register Offsets
#define ADC_ACTSS_OFFSET    0x000
#define ADC_RIS_OFFSET      0x004
#define ADC_IM_OFFSET       0x008
#define ADC_ISC_OFFSET      0x00C
#define ADC_OSTAT_OFFSET    0x010
#define ADC_EMUX_OFFSET     0x014
#define ADC_USTAT_OFFSET    0x018
#define ADC_TSSEL_OFFSET    0x01C
#define ADC_SSPRI_OFFSET    0x020
#define ADC_SPC_OFFSET      0x024
#define ADC_PSSI_OFFSET     0x028
#define ADC_SAC_OFFSET      0x030
#define ADC_DCISC_OFFSET    0x034
#define ADC_CTL_OFFSET      0x038
#define ADC_SSMUX0_OFFSET   0x040
#define ADC_SSCTL0_OFFSET   0x044
#define ADC_SSFIFO0_OFFSET  0x048
#define ADC_SSFSTAT0_OFFSET 0x04C
#define ADC_SSOP0_OFFSET    0x050
#define ADC_SSDC0_OFFSET    0x054
#define ADC_SSEMUX0_OFFSET  0x058
#define ADC_SSTSH0_OFFSET   0x05C
#define ADC_SSMUX1_OFFSET   0x060
#define ADC_SSCTL1_OFFSET   0x064
#define ADC_SSFIFO1_OFFSET  0x068
#define ADC_SSFSTAT1_OFFSET 0x06C
#define ADC_SSOP1_OFFSET    0x070
#define ADC_SSDC1_OFFSET    0x074
#define ADC_SSEMUX1_OFFSET  0x078
#define ADC_SSTSH1_OFFSET   0x07C
#define ADC_SSMUX2_OFFSET   0x080
#define ADC_SSCTL2_OFFSET   0x084
#define ADC_SSFIFO2_OFFSET  0x088
#define ADC_SSFSTAT2_OFFSET 0x08C
#define ADC_SSOP2_OFFSET    0x090
#define ADC_SSDC2_OFFSET    0x094
#define ADC_SSEMUX2_OFFSET  0x098
#define ADC_SSTSH2_OFFSET   0x09C
#define ADC_SSMUX3_OFFSET   0x0A0
#define ADC_SSCTL3_OFFSET   0x0A4
#define ADC_SSFIFO3_OFFSET  0x0A8
#define ADC_SSFSTAT3_OFFSET 0x0AC
#define ADC_SSOP3_OFFSET    0x0B0
#define ADC_SSDC3_OFFSET    0x0B4
#define ADC_SSEMUX3_OFFSET  0x0B8
#define ADC_SSTSH3_OFFSET   0x0BC
#define ADC_DCRIC_OFFSET    0xD00
#define ADC_DCCTL0_OFFSET   0xE00
#define ADC_DCCTL1_OFFSET   0xE04
#define ADC_DCCTL2_OFFSET   0xE08
#define ADC_DCCTL3_OFFSET   0xE0C
#define ADC_DCCTL4_OFFSET   0xE10
#define ADC_DCCTL5_OFFSET   0xE14
#define ADC_DCCTL6_OFFSET   0xE18
#define ADC_DCCTL7_OFFSET   0xE1C
#define ADC_DCCMP0_OFFSET   0xE40
#define ADC_DCCMP1_OFFSET   0xE44
#define ADC_DCCMP2_OFFSET   0xE48
#define ADC_DCCMP3_OFFSET   0xE4C
#define ADC_DCCMP4_OFFSET   0xE50
#define ADC_DCCMP5_OFFSET   0xE54
#define ADC_DCCMP6_OFFSET   0xE58
#define ADC_DCCMP7_OFFSET   0xE5C
#define ADC_PP_OFFSET       0xFC0
#define ADC_PC_OFFSET       0xFC4
#define ADC_CC_OFFSET       0xFC8


// ADC 0 Registers
#define ADC_0_BASE 0x40038000
#define ADC_0_ACTSS    REGISTER(ADC_0_BASE + ADC_ACTSS_OFFSET)
#define ADC_0_RIS      REGISTER(ADC_0_BASE + ADC_RIS_OFFSET)
#define ADC_0_IM       REGISTER(ADC_0_BASE + ADC_IM_OFFSET)
#define ADC_0_ISC      REGISTER(ADC_0_BASE + ADC_ISC_OFFSET)
#define ADC_0_OSTAT    REGISTER(ADC_0_BASE + ADC_OSTAT_OFFSET)
#define ADC_0_EMUX     REGISTER(ADC_0_BASE + ADC_EMUX_OFFSET)
#define ADC_0_USTAT    REGISTER(ADC_0_BASE + ADC_USTAT_OFFSET)
#define ADC_0_TSSEL    REGISTER(ADC_0_BASE + ADC_TSSEL_OFFSET)
#define ADC_0_SSPRI    REGISTER(ADC_0_BASE + ADC_SSPRI_OFFSET)
#define ADC_0_SPC      REGISTER(ADC_0_BASE + ADC_SPC_OFFSET)
#define ADC_0_PSSI     REGISTER(ADC_0_BASE + ADC_PSSI_OFFSET)
#define ADC_0_SAC      REGISTER(ADC_0_BASE + ADC_SAC_OFFSET)
#define ADC_0_DCISC    REGISTER(ADC_0_BASE + ADC_DCISC_OFFSET)
#define ADC_0_CTL      REGISTER(ADC_0_BASE + ADC_CTL_OFFSET)
#define ADC_0_SSMUX0   REGISTER(ADC_0_BASE + ADC_SSMUX0_OFFSET)
#define ADC_0_SSCTL0   REGISTER(ADC_0_BASE + ADC_SSCTL0_OFFSET)
#define ADC_0_SSFIFO0  REGISTER(ADC_0_BASE + ADC_SSFIFO0_OFFSET)
#define ADC_0_SSFSTAT0 REGISTER(ADC_0_BASE + ADC_SSFSTAT0_OFFSET)
#define ADC_0_SSOP0    REGISTER(ADC_0_BASE + ADC_SSOP0_OFFSET)
#define ADC_0_SSDC0    REGISTER(ADC_0_BASE + ADC_SSDC0_OFFSET)
#define ADC_0_SSEMUX0  REGISTER(ADC_0_BASE + ADC_SSEMUX0_OFFSET)
#define ADC_0_SSTSH0   REGISTER(ADC_0_BASE + ADC_SSTSH0_OFFSET)
#define ADC_0_SSMUX1   REGISTER(ADC_0_BASE + ADC_SSMUX1_OFFSET)
#define ADC_0_SSCTL1   REGISTER(ADC_0_BASE + ADC_SSCTL1_OFFSET)
#define ADC_0_SSFIFO1  REGISTER(ADC_0_BASE + ADC_SSFIFO1_OFFSET)
#define ADC_0_SSFSTAT1 REGISTER(ADC_0_BASE + ADC_SSFSTAT1_OFFSET)
#define ADC_0_SSOP1    REGISTER(ADC_0_BASE + ADC_SSOP1_OFFSET)
#define ADC_0_SSDC1    REGISTER(ADC_0_BASE + ADC_SSDC1_OFFSET)
#define ADC_0_SSEMUX1  REGISTER(ADC_0_BASE + ADC_SSEMUX1_OFFSET)
#define ADC_0_SSTSH1   REGISTER(ADC_0_BASE + ADC_SSTSH1_OFFSET)
#define ADC_0_SSMUX2   REGISTER(ADC_0_BASE + ADC_SSMUX2_OFFSET)
#define ADC_0_SSCTL2   REGISTER(ADC_0_BASE + ADC_SSCTL2_OFFSET)
#define ADC_0_SSFIFO2  REGISTER(ADC_0_BASE + ADC_SSFIFO2_OFFSET)
#define ADC_0_SSFSTAT2 REGISTER(ADC_0_BASE + ADC_SSFSTAT2_OFFSET)
#define ADC_0_SSOP2    REGISTER(ADC_0_BASE + ADC_SSOP2_OFFSET)
#define ADC_0_SSDC2    REGISTER(ADC_0_BASE + ADC_SSDC2_OFFSET)
#define ADC_0_SSEMUX2  REGISTER(ADC_0_BASE + ADC_SSEMUX2_OFFSET)
#define ADC_0_SSTSH2   REGISTER(ADC_0_BASE + ADC_SSTSH2_OFFSET)
#define ADC_0_SSMUX3   REGISTER(ADC_0_BASE + ADC_SSMUX3_OFFSET)
#define ADC_0_SSCTL3   REGISTER(ADC_0_BASE + ADC_SSCTL3_OFFSET)
#define ADC_0_SSFIFO3  REGISTER(ADC_0_BASE + ADC_SSFIFO3_OFFSET)
#define ADC_0_SSFSTAT3 REGISTER(ADC_0_BASE + ADC_SSFSTAT3_OFFSET)
#define ADC_0_SSOP3    REGISTER(ADC_0_BASE + ADC_SSOP3_OFFSET)
#define ADC_0_SSDC3    REGISTER(ADC_0_BASE + ADC_SSDC3_OFFSET)
#define ADC_0_SSEMUX3  REGISTER(ADC_0_BASE + ADC_SSEMUX3_OFFSET)
#define ADC_0_SSTSH3   REGISTER(ADC_0_BASE + ADC_SSTSH3_OFFSET)
#define ADC_0_DCRIC    REGISTER(ADC_0_BASE + ADC_DCRIC_OFFSET)
#define ADC_0_DCCTL0   REGISTER(ADC_0_BASE + ADC_DCCTL0_OFFSET)
#define ADC_0_DCCTL1   REGISTER(ADC_0_BASE + ADC_DCCTL1_OFFSET)
#define ADC_0_DCCTL2   REGISTER(ADC_0_BASE + ADC_DCCTL2_OFFSET)
#define ADC_0_DCCTL4   REGISTER(ADC_0_BASE + ADC_DCCTL4_OFFSET)
#define ADC_0_DCCTL5   REGISTER(ADC_0_BASE + ADC_DCCTL5_OFFSET)
#define ADC_0_DCCTL6   REGISTER(ADC_0_BASE + ADC_DCCTL6_OFFSET)
#define ADC_0_DCCTL7   REGISTER(ADC_0_BASE + ADC_DCCTL7_OFFSET)
#define ADC_0_DCCMP0   REGISTER(ADC_0_BASE + ADC_DCCMP0_OFFSET)
#define ADC_0_DCCMP1   REGISTER(ADC_0_BASE + ADC_DCCMP1_OFFSET)
#define ADC_0_DCCMP2   REGISTER(ADC_0_BASE + ADC_DCCMP2_OFFSET)
#define ADC_0_DCCMP3   REGISTER(ADC_0_BASE + ADC_DCCMP3_OFFSET)
#define ADC_0_DCCMP4   REGISTER(ADC_0_BASE + ADC_DCCMP4_OFFSET)
#define ADC_0_DCCMP5   REGISTER(ADC_0_BASE + ADC_DCCMP5_OFFSET)
#define ADC_0_DCCMP6   REGISTER(ADC_0_BASE + ADC_DCCMP6_OFFSET)
#define ADC_0_DCCMP7   REGISTER(ADC_0_BASE + ADC_DCCMP7_OFFSET)
#define ADC_0_PP       REGISTER(ADC_0_BASE + ADC_PP_OFFSET)
#define ADC_0_PC       REGISTER(ADC_0_BASE + ADC_PC_OFFSET)
#define ADC_0_CC       REGISTER(ADC_0_BASE + ADC_CC_OFFSET)


// ADC 1 Registers
#define ADC_1_BASE 0x40039000
#define ADC_1_ACTSS    REGISTER(ADC_1_BASE + ADC_ACTSS_OFFSET)
#define ADC_1_RIS      REGISTER(ADC_1_BASE + ADC_RIS_OFFSET)
#define ADC_1_IM       REGISTER(ADC_1_BASE + ADC_IM_OFFSET)
#define ADC_1_ISC      REGISTER(ADC_1_BASE + ADC_ISC_OFFSET)
#define ADC_1_OSTAT    REGISTER(ADC_1_BASE + ADC_OSTAT_OFFSET)
#define ADC_1_EMUX     REGISTER(ADC_1_BASE + ADC_EMUX_OFFSET)
#define ADC_1_USTAT    REGISTER(ADC_1_BASE + ADC_USTAT_OFFSET)
#define ADC_1_TSSEL    REGISTER(ADC_1_BASE + ADC_TSSEL_OFFSET)
#define ADC_1_SSPRI    REGISTER(ADC_1_BASE + ADC_SSPRI_OFFSET)
#define ADC_1_SPC      REGISTER(ADC_1_BASE + ADC_SPC_OFFSET)
#define ADC_1_PSSI     REGISTER(ADC_1_BASE + ADC_PSSI_OFFSET)
#define ADC_1_SAC      REGISTER(ADC_1_BASE + ADC_SAC_OFFSET)
#define ADC_1_DCISC    REGISTER(ADC_1_BASE + ADC_DCISC_OFFSET)
#define ADC_1_CTL      REGISTER(ADC_1_BASE + ADC_CTL_OFFSET)
#define ADC_1_SSMUX0   REGISTER(ADC_1_BASE + ADC_SSMUX0_OFFSET)
#define ADC_1_SSCTL0   REGISTER(ADC_1_BASE + ADC_SSCTL0_OFFSET)
#define ADC_1_SSFIFO0  REGISTER(ADC_1_BASE + ADC_SSFIFO0_OFFSET)
#define ADC_1_SSFSTAT0 REGISTER(ADC_1_BASE + ADC_SSFSTAT0_OFFSET)
#define ADC_1_SSOP0    REGISTER(ADC_1_BASE + ADC_SSOP0_OFFSET)
#define ADC_1_SSDC0    REGISTER(ADC_1_BASE + ADC_SSDC0_OFFSET)
#define ADC_1_SSEMUX0  REGISTER(ADC_1_BASE + ADC_SSEMUX0_OFFSET)
#define ADC_1_SSTSH0   REGISTER(ADC_1_BASE + ADC_SSTSH0_OFFSET)
#define ADC_1_SSMUX1   REGISTER(ADC_1_BASE + ADC_SSMUX1_OFFSET)
#define ADC_1_SSCTL1   REGISTER(ADC_1_BASE + ADC_SSCTL1_OFFSET)
#define ADC_1_SSFIFO1  REGISTER(ADC_1_BASE + ADC_SSFIFO1_OFFSET)
#define ADC_1_SSFSTAT1 REGISTER(ADC_1_BASE + ADC_SSFSTAT1_OFFSET)
#define ADC_1_SSOP1    REGISTER(ADC_1_BASE + ADC_SSOP1_OFFSET)
#define ADC_1_SSDC1    REGISTER(ADC_1_BASE + ADC_SSDC1_OFFSET)
#define ADC_1_SSEMUX1  REGISTER(ADC_1_BASE + ADC_SSEMUX1_OFFSET)
#define ADC_1_SSTSH1   REGISTER(ADC_1_BASE + ADC_SSTSH1_OFFSET)
#define ADC_1_SSMUX2   REGISTER(ADC_1_BASE + ADC_SSMUX2_OFFSET)
#define ADC_1_SSCTL2   REGISTER(ADC_1_BASE + ADC_SSCTL2_OFFSET)
#define ADC_1_SSFIFO2  REGISTER(ADC_1_BASE + ADC_SSFIFO2_OFFSET)
#define ADC_1_SSFSTAT2 REGISTER(ADC_1_BASE + ADC_SSFSTAT2_OFFSET)
#define ADC_1_SSOP2    REGISTER(ADC_1_BASE + ADC_SSOP2_OFFSET)
#define ADC_1_SSDC2    REGISTER(ADC_1_BASE + ADC_SSDC2_OFFSET)
#define ADC_1_SSEMUX2  REGISTER(ADC_1_BASE + ADC_SSEMUX2_OFFSET)
#define ADC_1_SSTSH2   REGISTER(ADC_1_BASE + ADC_SSTSH2_OFFSET)
#define ADC_1_SSMUX3   REGISTER(ADC_1_BASE + ADC_SSMUX3_OFFSET)
#define ADC_1_SSCTL3   REGISTER(ADC_1_BASE + ADC_SSCTL3_OFFSET)
#define ADC_1_SSFIFO3  REGISTER(ADC_1_BASE + ADC_SSFIFO3_OFFSET)
#define ADC_1_SSFSTAT3 REGISTER(ADC_1_BASE + ADC_SSFSTAT3_OFFSET)
#define ADC_1_SSOP3    REGISTER(ADC_1_BASE + ADC_SSOP3_OFFSET)
#define ADC_1_SSDC3    REGISTER(ADC_1_BASE + ADC_SSDC3_OFFSET)
#define ADC_1_SSEMUX3  REGISTER(ADC_1_BASE + ADC_SSEMUX3_OFFSET)
#define ADC_1_SSTSH3   REGISTER(ADC_1_BASE + ADC_SSTSH3_OFFSET)
#define ADC_1_DCRIC    REGISTER(ADC_1_BASE + ADC_DCRIC_OFFSET)
#define ADC_1_DCCTL0   REGISTER(ADC_1_BASE + ADC_DCCTL0_OFFSET)
#define ADC_1_DCCTL1   REGISTER(ADC_1_BASE + ADC_DCCTL1_OFFSET)
#define ADC_1_DCCTL2   REGISTER(ADC_1_BASE + ADC_DCCTL2_OFFSET)
#define ADC_1_DCCTL4   REGISTER(ADC_1_BASE + ADC_DCCTL4_OFFSET)
#define ADC_1_DCCTL5   REGISTER(ADC_1_BASE + ADC_DCCTL5_OFFSET)
#define ADC_1_DCCTL6   REGISTER(ADC_1_BASE + ADC_DCCTL6_OFFSET)
#define ADC_1_DCCTL7   REGISTER(ADC_1_BASE + ADC_DCCTL7_OFFSET)
#define ADC_1_DCCMP0   REGISTER(ADC_1_BASE + ADC_DCCMP0_OFFSET)
#define ADC_1_DCCMP1   REGISTER(ADC_1_BASE + ADC_DCCMP1_OFFSET)
#define ADC_1_DCCMP2   REGISTER(ADC_1_BASE + ADC_DCCMP2_OFFSET)
#define ADC_1_DCCMP3   REGISTER(ADC_1_BASE + ADC_DCCMP3_OFFSET)
#define ADC_1_DCCMP4   REGISTER(ADC_1_BASE + ADC_DCCMP4_OFFSET)
#define ADC_1_DCCMP5   REGISTER(ADC_1_BASE + ADC_DCCMP5_OFFSET)
#define ADC_1_DCCMP6   REGISTER(ADC_1_BASE + ADC_DCCMP6_OFFSET)
#define ADC_1_DCCMP7   REGISTER(ADC_1_BASE + ADC_DCCMP7_OFFSET)
#define ADC_1_PP       REGISTER(ADC_1_BASE + ADC_PP_OFFSET)
#define ADC_1_PC       REGISTER(ADC_1_BASE + ADC_PC_OFFSET)
#define ADC_1_CC       REGISTER(ADC_1_BASE + ADC_CC_OFFSET)

