#pragma once

#include "registers/register_helpers.h"

// Interrupt Enable / Disable
#define GIE() __asm__("CPSIE i");
#define GID() __asm__("CPSID i");

// Core Register Base
#define CORE_BASE 0xE000E000

// Core Register Offsets
#define CORE_STCTRL_OFFSET     0x010
#define CORE_STRELOAD_OFFSET   0x014
#define CORE_STCURRENT_OFFSET  0x018
#define CORE_EN0_OFFSET        0x100
#define CORE_EN1_OFFSET        0x104
#define CORE_EN2_OFFSET        0x108
#define CORE_EN3_OFFSET        0x10C
#define CORE_DIS0_OFFSET       0x180
#define CORE_DIS1_OFFSET       0x184
#define CORE_DIS2_OFFSET       0x188
#define CORE_DIS3_OFFSET       0x18C
#define CORE_PEND0_OFFSET      0x200
#define CORE_PEND1_OFFSET      0x204
#define CORE_PEND2_OFFSET      0x208
#define CORE_PEND3_OFFSET      0x20C
#define CORE_UNPEND0_OFFSET    0x280
#define CORE_UNPEND1_OFFSET    0x284
#define CORE_UNPEND2_OFFSET    0x288
#define CORE_UNPEND3_OFFSET    0x28C
#define CORE_ACTIVE0_OFFSET    0x300
#define CORE_ACTIVE1_OFFSET    0x304
#define CORE_ACTIVE2_OFFSET    0x308
#define CORE_ACTIVE3_OFFSET    0x30C
#define CORE_PRI0_OFFSET       0x400
#define CORE_PRI1_OFFSET       0x404
#define CORE_PRI2_OFFSET       0x408
#define CORE_PRI3_OFFSET       0x40C
#define CORE_PRI4_OFFSET       0x410
#define CORE_PRI5_OFFSET       0x414
#define CORE_PRI6_OFFSET       0x418
#define CORE_PRI7_OFFSET       0x41C
#define CORE_PRI8_OFFSET       0x420
#define CORE_PRI9_OFFSET       0x424
#define CORE_PRI10_OFFSET      0x428
#define CORE_PRI11_OFFSET      0x42C
#define CORE_PRI12_OFFSET      0x430
#define CORE_PRI13_OFFSET      0x434
#define CORE_PRI14_OFFSET      0x438
#define CORE_PRI15_OFFSET      0x43C
#define CORE_PRI16_OFFSET      0x440
#define CORE_PRI17_OFFSET      0x444
#define CORE_PRI18_OFFSET      0x448
#define CORE_PRI19_OFFSET      0x44C
#define CORE_PRI20_OFFSET      0x450
#define CORE_PRI21_OFFSET      0x454
#define CORE_PRI22_OFFSET      0x458
#define CORE_PRI23_OFFSET      0x45C
#define CORE_PRI24_OFFSET      0x460
#define CORE_PRI25_OFFSET      0x464
#define CORE_PRI26_OFFSET      0x468
#define CORE_PRI27_OFFSET      0x46C
#define CORE_PRI28_OFFSET      0x470
#define CORE_SWTRIG_OFFSET     0xF00
#define CORE_ACTLR_OFFSET      0x008
#define CORE_CPUID_OFFSET      0xD00
#define CORE_INTCTRL_OFFSET    0xD04
#define CORE_VTABLE_OFFSET     0xD08
#define CORE_APINT_OFFSET      0xD0C
#define CORE_SYSCTRL_OFFSET    0xD10
#define CORE_CFGCTRL_OFFSET    0xD14
#define CORE_SYSPRI1_OFFSET    0xD18
#define CORE_SYSPRI2_OFFSET    0xD1C
#define CORE_SYSPRI3_OFFSET    0xD20
#define CORE_SYSHNDCTRL_OFFSET 0xD24
#define CORE_FAULTSTAT_OFFSET  0xD28
#define CORE_HFAULTSTAT_OFFSET 0xD2C
#define CORE_MMADDR_OFFSET     0xD34
#define CORE_FAULTADDR_OFFSET  0xD38
#define CORE_MPUTYPE_OFFSET    0xD90
#define CORE_MPUCTRL_OFFSET    0xD94
#define CORE_MPUNUMBER_OFFSET  0xD98
#define CORE_MPUBASE_OFFSET    0xD9C
#define CORE_MPUATTR_OFFSET    0xDA0
#define CORE_MPUBASE1_OFFSET   0xDA4
#define CORE_MPUATTR1_OFFSET   0xDA8
#define CORE_MPUBASE2_OFFSET   0xDAC
#define CORE_MPUATTR2_OFFSET   0xDB0
#define CORE_MPUBASE3_OFFSET   0xDB4
#define CORE_MPUATTR3_OFFSET   0xDB8
#define CORE_CPAC_OFFSET       0xD88
#define CORE_FPCC_OFFSET       0xF34
#define CORE_FPCA_OFFSET       0xF38
#define CORE_FPDSC_OFFSET      0xF3C

// Core Register Defines
#define CORE_STCTRL     REGISTER(CORE_BASE + CORE_STCTRL_OFFSET)
#define CORE_STRELOAD   REGISTER(CORE_BASE + CORE_STRELOAD_OFFSET)
#define CORE_STCURRENT  REGISTER(CORE_BASE + CORE_STCURRENT_OFFSET)
#define CORE_EN0        REGISTER(CORE_BASE + CORE_EN0_OFFSET)
#define CORE_EN1        REGISTER(CORE_BASE + CORE_EN1_OFFSET)
#define CORE_EN2        REGISTER(CORE_BASE + CORE_EN2_OFFSET)
#define CORE_EN3        REGISTER(CORE_BASE + CORE_EN3_OFFSET)
#define CORE_DIS0       REGISTER(CORE_BASE + CORE_DIS0_OFFSET)
#define CORE_DIS1       REGISTER(CORE_BASE + CORE_DIS1_OFFSET)
#define CORE_DIS2       REGISTER(CORE_BASE + CORE_DIS2_OFFSET)
#define CORE_DIS3       REGISTER(CORE_BASE + CORE_DIS3_OFFSET)
#define CORE_PEND0      REGISTER(CORE_BASE + CORE_PEND0_OFFSET)
#define CORE_PEND1      REGISTER(CORE_BASE + CORE_PEND1_OFFSET)
#define CORE_PEND2      REGISTER(CORE_BASE + CORE_PEND2_OFFSET)
#define CORE_PEND3      REGISTER(CORE_BASE + CORE_PEND3_OFFSET)
#define CORE_UNPEND0    REGISTER(CORE_BASE + CORE_UNPEND0_OFFSET)
#define CORE_UNPEND1    REGISTER(CORE_BASE + CORE_UNPEND1_OFFSET)
#define CORE_UNPEND2    REGISTER(CORE_BASE + CORE_UNPEND2_OFFSET)
#define CORE_UNPEND3    REGISTER(CORE_BASE + CORE_UNPEND3_OFFSET)
#define CORE_ACTIVE0    REGISTER(CORE_BASE + CORE_ACTIVE0_OFFSET)
#define CORE_ACTIVE1    REGISTER(CORE_BASE + CORE_ACTIVE1_OFFSET)
#define CORE_ACTIVE2    REGISTER(CORE_BASE + CORE_ACTIVE2_OFFSET)
#define CORE_ACTIVE3    REGISTER(CORE_BASE + CORE_ACTIVE3_OFFSET)
#define CORE_PRI0       REGISTER(CORE_BASE + CORE_PRI0_OFFSET)
#define CORE_PRI1       REGISTER(CORE_BASE + CORE_PRI1_OFFSET)
#define CORE_PRI2       REGISTER(CORE_BASE + CORE_PRI2_OFFSET)
#define CORE_PRI3       REGISTER(CORE_BASE + CORE_PRI3_OFFSET)
#define CORE_PRI4       REGISTER(CORE_BASE + CORE_PRI4_OFFSET)
#define CORE_PRI5       REGISTER(CORE_BASE + CORE_PRI5_OFFSET)
#define CORE_PRI6       REGISTER(CORE_BASE + CORE_PRI6_OFFSET)
#define CORE_PRI7       REGISTER(CORE_BASE + CORE_PRI7_OFFSET)
#define CORE_PRI8       REGISTER(CORE_BASE + CORE_PRI8_OFFSET)
#define CORE_PRI9       REGISTER(CORE_BASE + CORE_PRI9_OFFSET)
#define CORE_PRI10      REGISTER(CORE_BASE + CORE_PRI10_OFFSET)
#define CORE_PRI11      REGISTER(CORE_BASE + CORE_PRI11_OFFSET)
#define CORE_PRI12      REGISTER(CORE_BASE + CORE_PRI12_OFFSET)
#define CORE_PRI13      REGISTER(CORE_BASE + CORE_PRI13_OFFSET)
#define CORE_PRI14      REGISTER(CORE_BASE + CORE_PRI14_OFFSET)
#define CORE_PRI15      REGISTER(CORE_BASE + CORE_PRI15_OFFSET)
#define CORE_PRI16      REGISTER(CORE_BASE + CORE_PRI16_OFFSET)
#define CORE_PRI17      REGISTER(CORE_BASE + CORE_PRI17_OFFSET)
#define CORE_PRI18      REGISTER(CORE_BASE + CORE_PRI18_OFFSET)
#define CORE_PRI19      REGISTER(CORE_BASE + CORE_PRI19_OFFSET)
#define CORE_PRI20      REGISTER(CORE_BASE + CORE_PRI20_OFFSET)
#define CORE_PRI21      REGISTER(CORE_BASE + CORE_PRI21_OFFSET)
#define CORE_PRI22      REGISTER(CORE_BASE + CORE_PRI22_OFFSET)
#define CORE_PRI23      REGISTER(CORE_BASE + CORE_PRI23_OFFSET)
#define CORE_PRI24      REGISTER(CORE_BASE + CORE_PRI24_OFFSET)
#define CORE_PRI25      REGISTER(CORE_BASE + CORE_PRI25_OFFSET)
#define CORE_PRI26      REGISTER(CORE_BASE + CORE_PRI26_OFFSET)
#define CORE_PRI27      REGISTER(CORE_BASE + CORE_PRI27_OFFSET)
#define CORE_PRI28      REGISTER(CORE_BASE + CORE_PRI28_OFFSET)
#define CORE_SWTRIG     REGISTER(CORE_BASE + CORE_SWTRIG_OFFSET)
#define CORE_ACTLR      REGISTER(CORE_BASE + CORE_ACTLR_OFFSET)
#define CORE_CPUID      REGISTER(CORE_BASE + CORE_CPUID_OFFSET)
#define CORE_INTCTRL    REGISTER(CORE_BASE + CORE_INTCTRL_OFFSET)
#define CORE_VTABLE     REGISTER(CORE_BASE + CORE_VTABLE_OFFSET)
#define CORE_APINT      REGISTER(CORE_BASE + CORE_APINT_OFFSET)
#define CORE_SYSCTRL    REGISTER(CORE_BASE + CORE_SYSCTRL_OFFSET)
#define CORE_CFGCTRL    REGISTER(CORE_BASE + CORE_CFGCTRL_OFFSET)
#define CORE_SYSPRI1    REGISTER(CORE_BASE + CORE_SYSPRI1_OFFSET)
#define CORE_SYSPRI2    REGISTER(CORE_BASE + CORE_SYSPRI2_OFFSET)
#define CORE_SYSPRI3    REGISTER(CORE_BASE + CORE_SYSPRI3_OFFSET)
#define CORE_SYSHNDCTRL REGISTER(CORE_BASE + CORE_SYSHNDCTRL_OFFSET)
#define CORE_FAULTSTAT  REGISTER(CORE_BASE + CORE_FAULTSTAT_OFFSET)
#define CORE_HFAULTSTAT REGISTER(CORE_BASE + CORE_HFAULTSTAT_OFFSET)
#define CORE_MMADDR     REGISTER(CORE_BASE + CORE_MMADDR_OFFSET)
#define CORE_FAULTADDR  REGISTER(CORE_BASE + CORE_FAULTADDR_OFFSET)
#define CORE_MPUTYPE    REGISTER(CORE_BASE + CORE_MPUTYPE_OFFSET)
#define CORE_MPUCTRL    REGISTER(CORE_BASE + CORE_MPUCTRL_OFFSET)
#define CORE_MPUNUMBER  REGISTER(CORE_BASE + CORE_MPUNUMBER_OFFSET)
#define CORE_MPUBASE    REGISTER(CORE_BASE + CORE_MPUBASE_OFFSET)
#define CORE_MPUATTR    REGISTER(CORE_BASE + CORE_MPUATTR_OFFSET)
#define CORE_MPUBASE1   REGISTER(CORE_BASE + CORE_MPUBASE1_OFFSET)
#define CORE_MPUATTR1   REGISTER(CORE_BASE + CORE_MPUATTR1_OFFSET)
#define CORE_MPUBASE2   REGISTER(CORE_BASE + CORE_MPUBASE2_OFFSET)
#define CORE_MPUATTR2   REGISTER(CORE_BASE + CORE_MPUATTR2_OFFSET)
#define CORE_MPUBASE3   REGISTER(CORE_BASE + CORE_MPUBASE3_OFFSET)
#define CORE_MPUATTR3   REGISTER(CORE_BASE + CORE_MPUATTR3_OFFSET)
#define CORE_CPAC       REGISTER(CORE_BASE + CORE_CPAC_OFFSET)
#define CORE_FPCC       REGISTER(CORE_BASE + CORE_FPCC_OFFSET)
#define CORE_FPCA       REGISTER(CORE_BASE + CORE_FPCA_OFFSET)
#define CORE_FPDSC      REGISTER(CORE_BASE + CORE_FPDSC_OFFSET)
