#pragma once

#include "registers/register_helpers.h"

// Ethernet MAC / PHY Base Address
#define EMAC_BASE 0x400EC000

// Ethernet MAC Register Offsets
#define EMAC_CFG_OFFSET          0x0000
#define EMAC_FRAMEFLTR_OFFSET    0x0004
#define EMAC_HASHTBLH_OFFSET     0x0008
#define EMAC_HASHTBLL_OFFSET     0x000C
#define EMAC_MIIADDR_OFFSET      0x0010
#define EMAC_MIIDATA_OFFSET      0x0014
#define EMAC_FLOWCTL_OFFSET      0x0018
#define EMAC_VLANTG_OFFSET       0x001C
#define EMAC_STATUS_OFFSET       0x0024
#define EMAC_RWUFF_OFFSET        0x0028
#define EMAC_PMTCTLSTAT_OFFSET   0x002C
#define EMAC_RIS_OFFSET          0x0038
#define EMAC_IM_OFFSET           0x003C
#define EMAC_ADDR0H_OFFSET       0x0040
#define EMAC_ADDR0L_OFFSET       0x0044
#define EMAC_ADDR1H_OFFSET       0x0048
#define EMAC_ADDR1L_OFFSET       0x004C
#define EMAC_ADDR2H_OFFSET       0x0050
#define EMAC_ADDR2L_OFFSET       0x0054
#define EMAC_ADDR3H_OFFSET       0x0058
#define EMAC_ADDR3L_OFFSET       0x005C
#define EMAC_WDOGTO_OFFSET       0x00DC
#define EMAC_MMCCTRL_OFFSET      0x0100
#define EMAC_MMCRXRIS_OFFSET     0x0104
#define EMAC_MMCTXRIS_OFFSET     0x0108
#define EMAC_MMCRXIM_OFFSET      0x010C
#define EMAC_MMCTXIM_OFFSET      0x0110
#define EMAC_TXCNTGB_OFFSET      0x0118
#define EMAC_TXCNTSCOL_OFFSET    0x014C
#define EMAC_TXCNTMCOL_OFFSET    0x0150
#define EMAC_TXOCTCNTG_OFFSET    0x0164
#define EMAC_RXCNTGB_OFFSET      0x0180
#define EMAC_RXCNTCRCERR_OFFSET  0x0194
#define EMAC_RXCNTALGNERR_OFFSET 0x0198
#define EMAC_RXCNTGUNI_OFFSET    0x01C4
#define EMAC_VLNINCREP_OFFSET    0x0584
#define EMAC_VLANHASH_OFFSET     0x0588
#define EMAC_TIMSTCTRL_OFFSET    0x0700
#define EMAC_SUBSECINC_OFFSET    0x0704
#define EMAC_TIMSEC_OFFSET       0x0708
#define EMAC_TIMNANO_OFFSET      0x070C
#define EMAC_TIMSECU_OFFSET      0x0710
#define EMAC_TIMNANOU_OFFSET     0x0714
#define EMAC_TIMADD_OFFSET       0x0718
#define EMAC_TARGSEC_OFFSET      0x071C
#define EMAC_TARGNANO_OFFSET     0x0720
#define EMAC_HWORDSEC_OFFSET     0x0724
#define EMAC_TIMSTAT_OFFSET      0x0728
#define EMAC_PPSCTRL_OFFSET      0x072C
#define EMAC_PPS0INTVL_OFFSET    0x0760
#define EMAC_PPS0WIDTH_OFFSET    0x0764
#define EMAC_DMABUSMOD_OFFSET    0x0C00
#define EMAC_TXPOLLD_OFFSET      0x0C04
#define EMAC_RXPOLLD_OFFSET      0x0C08
#define EMAC_RXDLADDR_OFFSET     0x0C0C
#define EMAC_TXDLADDR_OFFSET     0x0C10
#define EMAC_DMARIS_OFFSET       0x0C14
#define EMAC_DMAOPMODE_OFFSET    0x0C18
#define EMAC_DMAIM_OFFSET        0x0C1C
#define EMAC_MFBOC_OFFSET        0x0C20
#define EMAC_RXINTWDT_OFFSET     0x0C24
#define EMAC_HOSTXDESC_OFFSET    0x0C48
#define EMAC_HOSRXDESC_OFFSET    0x0C4C
#define EMAC_HOSTXBA_OFFSET      0x0C50
#define EMAC_HOSRXBA_OFFSET      0x0C54
#define EMAC_PP_OFFSET           0x0FC0
#define EMAC_PC_OFFSET           0x0FC4
#define EMAC_CC_OFFSET           0x0FC8

// Ethernet PHY Register Offsets
#define EPHY_RIS_OFFSET          0x0FD0
#define EPHY_IM_OFFSET           0x0FD4
#define EPHY_MISC_OFFSET         0x0FD8

// Ethernet MAC Registers
#define EMAC_CFG          REGISTER(EMAC_BASE + EMAC_CFG_OFFSET)
#define EMAC_FRAMEFLTR    REGISTER(EMAC_BASE + EMAC_FRAMEFLTR_OFFSET)
#define EMAC_HASHTBLH     REGISTER(EMAC_BASE + EMAC_HASHTBLH_OFFSET)
#define EMAC_HASHTBLL     REGISTER(EMAC_BASE + EMAC_HASHTBLL_OFFSET)
#define EMAC_MIIADDR      REGISTER(EMAC_BASE + EMAC_MIIADDR_OFFSET)
#define EMAC_MIIDATA      REGISTER(EMAC_BASE + EMAC_MIIDATA_OFFSET)
#define EMAC_FLOWCTL      REGISTER(EMAC_BASE + EMAC_FLOWCTL_OFFSET)
#define EMAC_VLANTG       REGISTER(EMAC_BASE + EMAC_VLANTG_OFFSET)
#define EMAC_STATUS       REGISTER(EMAC_BASE + EMAC_STATUS_OFFSET)
#define EMAC_RWUFF        REGISTER(EMAC_BASE + EMAC_RWUFF_OFFSET)
#define EMAC_PMTCTLSTAT   REGISTER(EMAC_BASE + EMAC_PMTCTLSTAT_OFFSET)
#define EMAC_RIS          REGISTER(EMAC_BASE + EMAC_RIS_OFFSET)
#define EMAC_IM           REGISTER(EMAC_BASE + EMAC_IM_OFFSET)
#define EMAC_ADDR0H       REGISTER(EMAC_BASE + EMAC_ADDR0H_OFFSET)
#define EMAC_ADDR0L       REGISTER(EMAC_BASE + EMAC_ADDR0L_OFFSET)
#define EMAC_ADDR1H       REGISTER(EMAC_BASE + EMAC_ADDR1H_OFFSET)
#define EMAC_ADDR1L       REGISTER(EMAC_BASE + EMAC_ADDR1L_OFFSET)
#define EMAC_ADDR2H       REGISTER(EMAC_BASE + EMAC_ADDR2H_OFFSET)
#define EMAC_ADDR2L       REGISTER(EMAC_BASE + EMAC_ADDR2L_OFFSET)
#define EMAC_ADDR3H       REGISTER(EMAC_BASE + EMAC_ADDR3H_OFFSET)
#define EMAC_ADDR3L       REGISTER(EMAC_BASE + EMAC_ADDR3L_OFFSET)
#define EMAC_WDOGTO       REGISTER(EMAC_BASE + EMAC_WDOGTO_OFFSET)
#define EMAC_MMCCTRL      REGISTER(EMAC_BASE + EMAC_MMCCTRL_OFFSET)
#define EMAC_MMCRXRIS     REGISTER(EMAC_BASE + EMAC_MMCRXRIS_OFFSET)
#define EMAC_MMCTXRIS     REGISTER(EMAC_BASE + EMAC_MMCTXRIS_OFFSET)
#define EMAC_MMCRXIM      REGISTER(EMAC_BASE + EMAC_MMCRXIM_OFFSET)
#define EMAC_MMCTXIM      REGISTER(EMAC_BASE + EMAC_MMCTXIM_OFFSET)
#define EMAC_TXCNTGB      REGISTER(EMAC_BASE + EMAC_TXCNTGB_OFFSET)
#define EMAC_TXCNTSCOL    REGISTER(EMAC_BASE + EMAC_TXCNTSCOL_OFFSET)
#define EMAC_TXCNTMCOL    REGISTER(EMAC_BASE + EMAC_TXCNTMCOL_OFFSET)
#define EMAC_TXOCTCNTG    REGISTER(EMAC_BASE + EMAC_TXOCTCNTG_OFFSET)
#define EMAC_RXCNTGB      REGISTER(EMAC_BASE + EMAC_RXCNTGB_OFFSET)
#define EMAC_RXCNTCRCERR  REGISTER(EMAC_BASE + EMAC_RXCNTCRCERR_OFFSET)
#define EMAC_RXCNTALGNERR REGISTER(EMAC_BASE + EMAC_RXCNTALGNERR_OFFSET)
#define EMAC_RXCNTGUNI    REGISTER(EMAC_BASE + EMAC_RXCNTGUNI_OFFSET)
#define EMAC_VLNINCREP    REGISTER(EMAC_BASE + EMAC_VLNINCREP_OFFSET)
#define EMAC_VLANHASH     REGISTER(EMAC_BASE + EMAC_VLANHASH_OFFSET)
#define EMAC_TIMSTCTRL    REGISTER(EMAC_BASE + EMAC_TIMSTCTRL_OFFSET)
#define EMAC_SUBSECINC    REGISTER(EMAC_BASE + EMAC_SUBSECINC_OFFSET)
#define EMAC_TIMSEC       REGISTER(EMAC_BASE + EMAC_TIMSEC_OFFSET)
#define EMAC_TIMNANO      REGISTER(EMAC_BASE + EMAC_TIMNANO_OFFSET)
#define EMAC_TIMSECU      REGISTER(EMAC_BASE + EMAC_TIMSECU_OFFSET)
#define EMAC_TIMNANOU     REGISTER(EMAC_BASE + EMAC_TIMNANOU_OFFSET)
#define EMAC_TIMADD       REGISTER(EMAC_BASE + EMAC_TIMADD_OFFSET)
#define EMAC_TARGSEC      REGISTER(EMAC_BASE + EMAC_TARGSEC_OFFSET)
#define EMAC_TARGNANO     REGISTER(EMAC_BASE + EMAC_TARGNANO_OFFSET)
#define EMAC_HWORDSEC     REGISTER(EMAC_BASE + EMAC_HWORDSEC_OFFSET)
#define EMAC_TIMSTAT      REGISTER(EMAC_BASE + EMAC_TIMSTAT_OFFSET)
#define EMAC_PPSCTRL      REGISTER(EMAC_BASE + EMAC_PPSCTRL_OFFSET)
#define EMAC_PPS0INTVL    REGISTER(EMAC_BASE + EMAC_PPS0INTVL_OFFSET)
#define EMAC_PPS0WIDTH    REGISTER(EMAC_BASE + EMAC_PPS0WIDTH_OFFSET)
#define EMAC_DMABUSMOD    REGISTER(EMAC_BASE + EMAC_DMABUSMOD_OFFSET)
#define EMAC_TXPOLLD      REGISTER(EMAC_BASE + EMAC_TXPOLLD_OFFSET)
#define EMAC_RXPOLLD      REGISTER(EMAC_BASE + EMAC_RXPOLLD_OFFSET)
#define EMAC_RXDLADDR     REGISTER(EMAC_BASE + EMAC_RXDLADDR_OFFSET)
#define EMAC_TXDLADDR     REGISTER(EMAC_BASE + EMAC_TXDLADDR_OFFSET)
#define EMAC_DMARIS       REGISTER(EMAC_BASE + EMAC_DMARIS_OFFSET)
#define EMAC_DMAOPMODE    REGISTER(EMAC_BASE + EMAC_DMAOPMODE_OFFSET)
#define EMAC_DMAIM        REGISTER(EMAC_BASE + EMAC_DMAIM_OFFSET)
#define EMAC_MFBOC        REGISTER(EMAC_BASE + EMAC_MFBOC_OFFSET)
#define EMAC_RXINTWDT     REGISTER(EMAC_BASE + EMAC_RXINTWDT_OFFSET)
#define EMAC_HOSTXDESC    REGISTER(EMAC_BASE + EMAC_HOSTXDESC_OFFSET)
#define EMAC_HOSRXDESC    REGISTER(EMAC_BASE + EMAC_HOSRXDESC_OFFSET)
#define EMAC_HOSTXBA      REGISTER(EMAC_BASE + EMAC_HOSTXBA_OFFSET)
#define EMAC_HOSRXBA      REGISTER(EMAC_BASE + EMAC_HOSRXBA_OFFSET)
#define EMAC_PP           REGISTER(EMAC_BASE + EMAC_PP_OFFSET)
#define EMAC_PC           REGISTER(EMAC_BASE + EMAC_PC_OFFSET)
#define EMAC_CC           REGISTER(EMAC_BASE + EMAC_CC_OFFSET)

// Ethernet PHY Registers
#define EPHY_RIS          REGISTER(EMAC_BASE + EPHY_RIS_OFFSET)
#define EPHY_IM           REGISTER(EMAC_BASE + EPHY_IM_OFFSET)
#define EPHY_MISC         REGISTER(EMAC_BASE + EPHY_MISC_OFFSET)

