/**
 * @brief All registers pertaining to PWM control
 */

#pragma once

#include "registers/register_helpers.h"

// PWM Base Address
#define PWM_BASE 0x40028000

// PWM Register offsets
#define PWM_CTL_OFFSET        0x000
#define PWM_SYNC_OFFSET       0x004
#define PWM_ENABLE_OFFSET     0x008
#define PWM_INVERT_OFFSET     0x00C
#define PWM_FAULT_OFFSET      0x010
#define PWM_INTEN_OFFSET      0x014
#define PWM_RIS_OFFSET        0x018
#define PWM_ISC_OFFSET        0x01C
#define PWM_STATUS_OFFSET     0x020
#define PWM_FAULTVAL_OFFSET   0x024
#define PWM_ENUPD_OFFSET      0x028
#define PWM_0CTL_OFFSET       0x040
#define PWM_0INTEN_OFFSET     0x044
#define PWM_0RIS_OFFSET       0x048
#define PWM_0ISC_OFFSET       0x04C
#define PWM_0LOAD_OFFSET      0x050
#define PWM_0COUNT_OFFSET     0x054
#define PWM_0CMPA_OFFSET      0x058
#define PWM_0CMPB_OFFSET      0x05C
#define PWM_0GENA_OFFSET      0x060
#define PWM_0GENB_OFFSET      0x064
#define PWM_0DBCTL_OFFSET     0x068
#define PWM_0DBRISE_OFFSET    0x06C
#define PWM_0DBFALL_OFFSET    0x070
#define PWM_0FLTSRC0_OFFSET   0x074
#define PWM_0FLTSRC1_OFFSET   0x078
#define PWM_0MINFLTPER_OFFSET 0x07C
#define PWM_1CTL_OFFSET       0x080
#define PWM_1INTEN_OFFSET     0x084
#define PWM_1RIS_OFFSET       0x088
#define PWM_1ISC_OFFSET       0x08C
#define PWM_1LOAD_OFFSET      0x090
#define PWM_1COUNT_OFFSET     0x094
#define PWM_1CMPA_OFFSET      0x098
#define PWM_1CMPB_OFFSET      0x09C
#define PWM_1GENA_OFFSET      0x0A0
#define PWM_1GENB_OFFSET      0x0A4
#define PWM_1DBCTL_OFFSET     0x0A8
#define PWM_1DBRISE_OFFSET    0x0AC
#define PWM_1DBFALL_OFFSET    0x0B0
#define PWM_1FLTSRC0_OFFSET   0x0B4
#define PWM_1FLTSRC1_OFFSET   0x0B8
#define PWM_1MINFLTPER_OFFSET 0x0BC
#define PWM_2CTL_OFFSET       0x0C0
#define PWM_2INTEN_OFFSET     0x0C4
#define PWM_2RIS_OFFSET       0x0C8
#define PWM_2ISC_OFFSET       0x0CC
#define PWM_2LOAD_OFFSET      0x0D0
#define PWM_2COUNT_OFFSET     0x0D4
#define PWM_2CMPA_OFFSET      0x0D8
#define PWM_2CMPB_OFFSET      0x0DC
#define PWM_2GENA_OFFSET      0x0E0
#define PWM_2GENB_OFFSET      0x0E4
#define PWM_2DBCTL_OFFSET     0x0E8
#define PWM_2DBRISE_OFFSET    0x0EC
#define PWM_2DBFALL_OFFSET    0x0F0
#define PWM_2FLTSRC0_OFFSET   0x0F4
#define PWM_2FLTSRC1_OFFSET   0x0F8
#define PWM_2MINFLTPER_OFFSET 0x0FC
#define PWM_3CTL_OFFSET       0x100
#define PWM_3INTEN_OFFSET     0x104
#define PWM_3RIS_OFFSET       0x108
#define PWM_3ISC_OFFSET       0x10C
#define PWM_3LOAD_OFFSET      0x110
#define PWM_3COUNT_OFFSET     0x114
#define PWM_3CMPA_OFFSET      0x118
#define PWM_3CMPB_OFFSET      0x11C
#define PWM_3GENA_OFFSET      0x120
#define PWM_3GENB_OFFSET      0x124
#define PWM_3DBCTL_OFFSET     0x128
#define PWM_3DBRISE_OFFSET    0x12C
#define PWM_3DBFALL_OFFSET    0x130
#define PWM_3FLTSRC0_OFFSET   0x134
#define PWM_3FLTSRC1_OFFSET   0x138
#define PWM_3MINFLTPER_OFFSET 0x13C
#define PWM_0FLTSEN_OFFSET    0x800
#define PWM_0FLTSTAT0_OFFSET  0x804
#define PWM_0FLTSTAT1_OFFSET  0x808
#define PWM_1FLTSEN_OFFSET    0x880
#define PWM_1FLTSTAT0_OFFSET  0x884
#define PWM_1FLTSTAT1_OFFSET  0x888
#define PWM_2FLTSEN_OFFSET    0x900
#define PWM_2FLTSTAT0_OFFSET  0x904
#define PWM_2FLTSTAT1_OFFSET  0x908
#define PWM_3FLTSEN_OFFSET    0x980
#define PWM_3FLTSTAT0_OFFSET  0x984
#define PWM_3FLTSTAT1_OFFSET  0x988
#define PWM_PP_OFFSET         0xFC0
#define PWM_CC_OFFSET         0xFC8

// PWM Registers
#define PWM_CTL        REGISTER(PWM_BASE + PWM_CTL_OFFSET)
#define PWM_SYNC       REGISTER(PWM_BASE + PWM_SYNC_OFFSET)
#define PWM_ENABLE     REGISTER(PWM_BASE + PWM_ENABLE_OFFSET)
#define PWM_INVERT     REGISTER(PWM_BASE + PWM_INVERT_OFFSET)
#define PWM_FAULT      REGISTER(PWM_BASE + PWM_FAULT_OFFSET)
#define PWM_INTEN      REGISTER(PWM_BASE + PWM_INTEN_OFFSET)
#define PWM_RIS        REGISTER(PWM_BASE + PWM_RIS_OFFSET)
#define PWM_ISC        REGISTER(PWM_BASE + PWM_ISC_OFFSET)
#define PWM_STATUS     REGISTER(PWM_BASE + PWM_STATUS_OFFSET)
#define PWM_FAULTVAL   REGISTER(PWM_BASE + PWM_FAULTVAL_OFFSET)
#define PWM_ENUPD      REGISTER(PWM_BASE + PWM_ENUPD_OFFSET)
#define PWM_0CTL       REGISTER(PWM_BASE + PWM_0CTL_OFFSET)
#define PWM_0INTEN     REGISTER(PWM_BASE + PWM_0INTEN_OFFSET)
#define PWM_0RIS       REGISTER(PWM_BASE + PWM_0RIS_OFFSET)
#define PWM_0ISC       REGISTER(PWM_BASE + PWM_0ISC_OFFSET)
#define PWM_0LOAD      REGISTER(PWM_BASE + PWM_0LOAD_OFFSET)
#define PWM_0COUNT     REGISTER(PWM_BASE + PWM_0COUNT_OFFSET)
#define PWM_0CMPA      REGISTER(PWM_BASE + PWM_0CMPA_OFFSET)
#define PWM_0CMPB      REGISTER(PWM_BASE + PWM_0CMPB_OFFSET)
#define PWM_0GENA      REGISTER(PWM_BASE + PWM_0GENA_OFFSET)
#define PWM_0GENB      REGISTER(PWM_BASE + PWM_0GENB_OFFSET)
#define PWM_0DBCTL     REGISTER(PWM_BASE + PWM_0DBCTL_OFFSET)
#define PWM_0DBRISE    REGISTER(PWM_BASE + PWM_0DBRISE_OFFSET)
#define PWM_0DBFALL    REGISTER(PWM_BASE + PWM_0DBFALL_OFFSET)
#define PWM_0FLTSRC0   REGISTER(PWM_BASE + PWM_0FLTSRC0_OFFSET)
#define PWM_0FLTSRC1   REGISTER(PWM_BASE + PWM_0FLTSRC1_OFFSET)
#define PWM_0MINFLTPER REGISTER(PWM_BASE + PWM_0MINFLTPER_OFFSET)
#define PWM_1CTL       REGISTER(PWM_BASE + PWM_1CTL_OFFSET)
#define PWM_1INTEN     REGISTER(PWM_BASE + PWM_1INTEN_OFFSET)
#define PWM_1RIS       REGISTER(PWM_BASE + PWM_1RIS_OFFSET)
#define PWM_1ISC       REGISTER(PWM_BASE + PWM_1ISC_OFFSET)
#define PWM_1LOAD      REGISTER(PWM_BASE + PWM_1LOAD_OFFSET)
#define PWM_1COUNT     REGISTER(PWM_BASE + PWM_1COUNT_OFFSET)
#define PWM_1CMPA      REGISTER(PWM_BASE + PWM_1CMPA_OFFSET)
#define PWM_1CMPB      REGISTER(PWM_BASE + PWM_1CMPB_OFFSET)
#define PWM_1GENA      REGISTER(PWM_BASE + PWM_1GENA_OFFSET)
#define PWM_1GENB      REGISTER(PWM_BASE + PWM_1GENB_OFFSET)
#define PWM_1DBCTL     REGISTER(PWM_BASE + PWM_1DBCTL_OFFSET)
#define PWM_1DBRISE    REGISTER(PWM_BASE + PWM_1DBRISE_OFFSET)
#define PWM_1DBFALL    REGISTER(PWM_BASE + PWM_1DBFALL_OFFSET)
#define PWM_1FLTSRC0   REGISTER(PWM_BASE + PWM_1FLTSRC0_OFFSET)
#define PWM_1FLTSRC1   REGISTER(PWM_BASE + PWM_1FLTSRC1_OFFSET)
#define PWM_1MINFLTPER REGISTER(PWM_BASE + PWM_1MINFLTPER_OFFSET)
#define PWM_2CTL       REGISTER(PWM_BASE + PWM_2CTL_OFFSET)
#define PWM_2INTEN     REGISTER(PWM_BASE + PWM_2INTEN_OFFSET)
#define PWM_2RIS       REGISTER(PWM_BASE + PWM_2RIS_OFFSET)
#define PWM_2ISC       REGISTER(PWM_BASE + PWM_2ISC_OFFSET)
#define PWM_2LOAD      REGISTER(PWM_BASE + PWM_2LOAD_OFFSET)
#define PWM_2COUNT     REGISTER(PWM_BASE + PWM_2COUNT_OFFSET)
#define PWM_2CMPA      REGISTER(PWM_BASE + PWM_2CMPA_OFFSET)
#define PWM_2CMPB      REGISTER(PWM_BASE + PWM_2CMPB_OFFSET)
#define PWM_2GENA      REGISTER(PWM_BASE + PWM_2GENA_OFFSET)
#define PWM_2GENB      REGISTER(PWM_BASE + PWM_2GENB_OFFSET)
#define PWM_2DBCTL     REGISTER(PWM_BASE + PWM_2DBCTL_OFFSET)
#define PWM_2DBRISE    REGISTER(PWM_BASE + PWM_2DBRISE_OFFSET)
#define PWM_2DBFALL    REGISTER(PWM_BASE + PWM_2DBFALL_OFFSET)
#define PWM_2FLTSRC0   REGISTER(PWM_BASE + PWM_2FLTSRC0_OFFSET)
#define PWM_2FLTSRC1   REGISTER(PWM_BASE + PWM_2FLTSRC1_OFFSET)
#define PWM_2MINFLTPER REGISTER(PWM_BASE + PWM_2MINFLTPER_OFFSET)
#define PWM_3CTL       REGISTER(PWM_BASE + PWM_3CTL_OFFSET)
#define PWM_3INTEN     REGISTER(PWM_BASE + PWM_3INTEN_OFFSET)
#define PWM_3RIS       REGISTER(PWM_BASE + PWM_3RIS_OFFSET)
#define PWM_3ISC       REGISTER(PWM_BASE + PWM_3ISC_OFFSET)
#define PWM_3LOAD      REGISTER(PWM_BASE + PWM_3LOAD_OFFSET)
#define PWM_3COUNT     REGISTER(PWM_BASE + PWM_3COUNT_OFFSET)
#define PWM_3CMPA      REGISTER(PWM_BASE + PWM_3CMPA_OFFSET)
#define PWM_3CMPB      REGISTER(PWM_BASE + PWM_3CMPB_OFFSET)
#define PWM_3GENA      REGISTER(PWM_BASE + PWM_3GENA_OFFSET)
#define PWM_3GENB      REGISTER(PWM_BASE + PWM_3GENB_OFFSET)
#define PWM_3DBCTL     REGISTER(PWM_BASE + PWM_3DBCTL_OFFSET)
#define PWM_3DBRISE    REGISTER(PWM_BASE + PWM_3DBRISE_OFFSET)
#define PWM_3DBFALL    REGISTER(PWM_BASE + PWM_3DBFALL_OFFSET)
#define PWM_3FLTSRC0   REGISTER(PWM_BASE + PWM_3FLTSRC0_OFFSET)
#define PWM_3FLTSRC1   REGISTER(PWM_BASE + PWM_3FLTSRC1_OFFSET)
#define PWM_3MINFLTPER REGISTER(PWM_BASE + PWM_3MINFLTPER_OFFSET)
#define PWM_0FLTSEN    REGISTER(PWM_BASE + PWM_0FLTSEN_OFFSET)
#define PWM_0FLTSTAT0  REGISTER(PWM_BASE + PWM_0FLTSTAT0_OFFSET)
#define PWM_0FLTSTAT1  REGISTER(PWM_BASE + PWM_0FLTSTAT1_OFFSET)
#define PWM_1FLTSEN    REGISTER(PWM_BASE + PWM_1FLTSEN_OFFSET)
#define PWM_1FLTSTAT0  REGISTER(PWM_BASE + PWM_1FLTSTAT0_OFFSET)
#define PWM_1FLTSTAT1  REGISTER(PWM_BASE + PWM_1FLTSTAT1_OFFSET)
#define PWM_2FLTSEN    REGISTER(PWM_BASE + PWM_2FLTSEN_OFFSET)
#define PWM_2FLTSTAT0  REGISTER(PWM_BASE + PWM_2FLTSTAT0_OFFSET)
#define PWM_2FLTSTAT1  REGISTER(PWM_BASE + PWM_2FLTSTAT1_OFFSET)
#define PWM_3FLTSEN    REGISTER(PWM_BASE + PWM_3FLTSEN_OFFSET)
#define PWM_3FLTSTAT0  REGISTER(PWM_BASE + PWM_3FLTSTAT0_OFFSET)
#define PWM_3FLTSTAT1  REGISTER(PWM_BASE + PWM_3FLTSTAT1_OFFSET)
#define PWM_PP         REGISTER(PWM_BASE + PWM_PP_OFFSET)
#define PWM_CC         REGISTER(PWM_BASE + PWM_CC_OFFSET)

