#pragma once

#include "registers/register_helpers.h"

// SSI Register Offsets
#define SSI_CR0_OFFSET       0x00000000
#define SSI_CR1_OFFSET       0x00000004
#define SSI_DR_OFFSET        0x00000008
#define SSI_SR_OFFSET        0x0000000C
#define SSI_CPSR_OFFSET      0x00000010
#define SSI_IM_OFFSET        0x00000014
#define SSI_RIS_OFFSET       0x00000018
#define SSI_MIS_OFFSET       0x0000001C
#define SSI_ICR_OFFSET       0x00000020
#define SSI_DMACTL_OFFSET    0x00000024
#define SSI_PP_OFFSET        0x00000FC0
#define SSI_CC_OFFSET        0x00000FC8
#define SSI_PeriphID4_OFFSET 0x00000FD0
#define SSI_PeriphID5_OFFSET 0x00000FD4
#define SSI_PeriphID6_OFFSET 0x00000FD8
#define SSI_PeriphID7_OFFSET 0x00000FDC
#define SSI_PeriphID0_OFFSET 0x00000FE0
#define SSI_PeriphID1_OFFSET 0x00000FE4
#define SSI_PeriphID2_OFFSET 0x00000FE8
#define SSI_PeriphID3_OFFSET 0x00000FEC
#define SSI_PCellID0_OFFSET  0x00000FF0
#define SSI_PCellID1_OFFSET  0x00000FF4
#define SSI_PCellID2_OFFSET  0x00000FF8
#define SSI_PCellID3_OFFSET  0x00000FFC

// SSI 0
#define SSI0_BASE 0x40008000
#define SSI0_CR0       REGISTER(SSI0_BASE + SSI_CR0_OFFSET)
#define SSI0_CR1       REGISTER(SSI0_BASE + SSI_CR1_OFFSET)
#define SSI0_DR        REGISTER(SSI0_BASE + SSI_DR_OFFSET)
#define SSI0_SR        REGISTER(SSI0_BASE + SSI_SR_OFFSET)
#define SSI0_CPSR      REGISTER(SSI0_BASE + SSI_CPSR_OFFSET)
#define SSI0_IM        REGISTER(SSI0_BASE + SSI_IM_OFFSET)
#define SSI0_RIS       REGISTER(SSI0_BASE + SSI_RIS_OFFSET)
#define SSI0_MIS       REGISTER(SSI0_BASE + SSI_MIS_OFFSET)
#define SSI0_ICR       REGISTER(SSI0_BASE + SSI_ICR_OFFSET)
#define SSI0_DMACTL    REGISTER(SSI0_BASE + SSI_DMACTL_OFFSET)
#define SSI0_PP        REGISTER(SSI0_BASE + SSI_PP_OFFSET)
#define SSI0_CC        REGISTER(SSI0_BASE + SSI_CC_OFFSET)
#define SSI0_PeriphID4 REGISTER(SSI0_BASE + SSI_PeriphID4_OFFSET)
#define SSI0_PeriphID5 REGISTER(SSI0_BASE + SSI_PeriphID5_OFFSET)
#define SSI0_PeriphID6 REGISTER(SSI0_BASE + SSI_PeriphID6_OFFSET)
#define SSI0_PeriphID7 REGISTER(SSI0_BASE + SSI_PeriphID7_OFFSET)
#define SSI0_PeriphID0 REGISTER(SSI0_BASE + SSI_PeriphID0_OFFSET)
#define SSI0_PeriphID1 REGISTER(SSI0_BASE + SSI_PeriphID1_OFFSET)
#define SSI0_PeriphID2 REGISTER(SSI0_BASE + SSI_PeriphID2_OFFSET)
#define SSI0_PeriphID3 REGISTER(SSI0_BASE + SSI_PeriphID3_OFFSET)
#define SSI0_PCellID0  REGISTER(SSI0_BASE + SSI_PCellID0_OFFSET)
#define SSI0_PCellID1  REGISTER(SSI0_BASE + SSI_PCellID1_OFFSET)
#define SSI0_PCellID2  REGISTER(SSI0_BASE + SSI_PCellID2_OFFSET)
#define SSI0_PCellID3  REGISTER(SSI0_BASE + SSI_PCellID3_OFFSET)

// SSI 1
#define SSI1_BASE 0x40009000
#define SSI1_CR0       REGISTER(SSI1_BASE + SSI_CR0_OFFSET)
#define SSI1_CR1       REGISTER(SSI1_BASE + SSI_CR1_OFFSET)
#define SSI1_DR        REGISTER(SSI1_BASE + SSI_DR_OFFSET)
#define SSI1_SR        REGISTER(SSI1_BASE + SSI_SR_OFFSET)
#define SSI1_CPSR      REGISTER(SSI1_BASE + SSI_CPSR_OFFSET)
#define SSI1_IM        REGISTER(SSI1_BASE + SSI_IM_OFFSET)
#define SSI1_RIS       REGISTER(SSI1_BASE + SSI_RIS_OFFSET)
#define SSI1_MIS       REGISTER(SSI1_BASE + SSI_MIS_OFFSET)
#define SSI1_ICR       REGISTER(SSI1_BASE + SSI_ICR_OFFSET)
#define SSI1_DMACTL    REGISTER(SSI1_BASE + SSI_DMACTL_OFFSET)
#define SSI1_PP        REGISTER(SSI1_BASE + SSI_PP_OFFSET)
#define SSI1_CC        REGISTER(SSI1_BASE + SSI_CC_OFFSET)
#define SSI1_PeriphID4 REGISTER(SSI1_BASE + SSI_PeriphID4_OFFSET)
#define SSI1_PeriphID5 REGISTER(SSI1_BASE + SSI_PeriphID5_OFFSET)
#define SSI1_PeriphID6 REGISTER(SSI1_BASE + SSI_PeriphID6_OFFSET)
#define SSI1_PeriphID7 REGISTER(SSI1_BASE + SSI_PeriphID7_OFFSET)
#define SSI1_PeriphID0 REGISTER(SSI1_BASE + SSI_PeriphID0_OFFSET)
#define SSI1_PeriphID1 REGISTER(SSI1_BASE + SSI_PeriphID1_OFFSET)
#define SSI1_PeriphID2 REGISTER(SSI1_BASE + SSI_PeriphID2_OFFSET)
#define SSI1_PeriphID3 REGISTER(SSI1_BASE + SSI_PeriphID3_OFFSET)
#define SSI1_PCellID0  REGISTER(SSI1_BASE + SSI_PCellID0_OFFSET)
#define SSI1_PCellID1  REGISTER(SSI1_BASE + SSI_PCellID1_OFFSET)
#define SSI1_PCellID2  REGISTER(SSI1_BASE + SSI_PCellID2_OFFSET)
#define SSI1_PCellID3  REGISTER(SSI1_BASE + SSI_PCellID3_OFFSET)

// SSI 2
#define SSI2_BASE 0x4000A000
#define SSI2_CR0       REGISTER(SSI2_BASE + SSI_CR0_OFFSET)
#define SSI2_CR1       REGISTER(SSI2_BASE + SSI_CR1_OFFSET)
#define SSI2_DR        REGISTER(SSI2_BASE + SSI_DR_OFFSET)
#define SSI2_SR        REGISTER(SSI2_BASE + SSI_SR_OFFSET)
#define SSI2_CPSR      REGISTER(SSI2_BASE + SSI_CPSR_OFFSET)
#define SSI2_IM        REGISTER(SSI2_BASE + SSI_IM_OFFSET)
#define SSI2_RIS       REGISTER(SSI2_BASE + SSI_RIS_OFFSET)
#define SSI2_MIS       REGISTER(SSI2_BASE + SSI_MIS_OFFSET)
#define SSI2_ICR       REGISTER(SSI2_BASE + SSI_ICR_OFFSET)
#define SSI2_DMACTL    REGISTER(SSI2_BASE + SSI_DMACTL_OFFSET)
#define SSI2_PP        REGISTER(SSI2_BASE + SSI_PP_OFFSET)
#define SSI2_CC        REGISTER(SSI2_BASE + SSI_CC_OFFSET)
#define SSI2_PeriphID4 REGISTER(SSI2_BASE + SSI_PeriphID4_OFFSET)
#define SSI2_PeriphID5 REGISTER(SSI2_BASE + SSI_PeriphID5_OFFSET)
#define SSI2_PeriphID6 REGISTER(SSI2_BASE + SSI_PeriphID6_OFFSET)
#define SSI2_PeriphID7 REGISTER(SSI2_BASE + SSI_PeriphID7_OFFSET)
#define SSI2_PeriphID0 REGISTER(SSI2_BASE + SSI_PeriphID0_OFFSET)
#define SSI2_PeriphID1 REGISTER(SSI2_BASE + SSI_PeriphID1_OFFSET)
#define SSI2_PeriphID2 REGISTER(SSI2_BASE + SSI_PeriphID2_OFFSET)
#define SSI2_PeriphID3 REGISTER(SSI2_BASE + SSI_PeriphID3_OFFSET)
#define SSI2_PCellID0  REGISTER(SSI2_BASE + SSI_PCellID0_OFFSET)
#define SSI2_PCellID1  REGISTER(SSI2_BASE + SSI_PCellID1_OFFSET)
#define SSI2_PCellID2  REGISTER(SSI2_BASE + SSI_PCellID2_OFFSET)
#define SSI2_PCellID3  REGISTER(SSI2_BASE + SSI_PCellID3_OFFSET)

// SSI 3
#define SSI3_BASE 0x4000B000
#define SSI3_CR0       REGISTER(SSI3_BASE + SSI_CR0_OFFSET)
#define SSI3_CR1       REGISTER(SSI3_BASE + SSI_CR1_OFFSET)
#define SSI3_DR        REGISTER(SSI3_BASE + SSI_DR_OFFSET)
#define SSI3_SR        REGISTER(SSI3_BASE + SSI_SR_OFFSET)
#define SSI3_CPSR      REGISTER(SSI3_BASE + SSI_CPSR_OFFSET)
#define SSI3_IM        REGISTER(SSI3_BASE + SSI_IM_OFFSET)
#define SSI3_RIS       REGISTER(SSI3_BASE + SSI_RIS_OFFSET)
#define SSI3_MIS       REGISTER(SSI3_BASE + SSI_MIS_OFFSET)
#define SSI3_ICR       REGISTER(SSI3_BASE + SSI_ICR_OFFSET)
#define SSI3_DMACTL    REGISTER(SSI3_BASE + SSI_DMACTL_OFFSET)
#define SSI3_PP        REGISTER(SSI3_BASE + SSI_PP_OFFSET)
#define SSI3_CC        REGISTER(SSI3_BASE + SSI_CC_OFFSET)
#define SSI3_PeriphID4 REGISTER(SSI3_BASE + SSI_PeriphID4_OFFSET)
#define SSI3_PeriphID5 REGISTER(SSI3_BASE + SSI_PeriphID5_OFFSET)
#define SSI3_PeriphID6 REGISTER(SSI3_BASE + SSI_PeriphID6_OFFSET)
#define SSI3_PeriphID7 REGISTER(SSI3_BASE + SSI_PeriphID7_OFFSET)
#define SSI3_PeriphID0 REGISTER(SSI3_BASE + SSI_PeriphID0_OFFSET)
#define SSI3_PeriphID1 REGISTER(SSI3_BASE + SSI_PeriphID1_OFFSET)
#define SSI3_PeriphID2 REGISTER(SSI3_BASE + SSI_PeriphID2_OFFSET)
#define SSI3_PeriphID3 REGISTER(SSI3_BASE + SSI_PeriphID3_OFFSET)
#define SSI3_PCellID0  REGISTER(SSI3_BASE + SSI_PCellID0_OFFSET)
#define SSI3_PCellID1  REGISTER(SSI3_BASE + SSI_PCellID1_OFFSET)
#define SSI3_PCellID2  REGISTER(SSI3_BASE + SSI_PCellID2_OFFSET)
#define SSI3_PCellID3  REGISTER(SSI3_BASE + SSI_PCellID3_OFFSET)
