#pragma once

#include "registers/register_helpers.h"

// System Control Register Base Address
#define SYSCTL_BASE 0x400FE000

// System Control Register Offsets
#define SYSCTL_DID0_OFFSET        0x00000000
#define SYSCTL_DID1_OFFSET        0x00000004
#define SYSCTL_PTBOCTL_OFFSET     0x00000038
#define SYSCTL_RIS_OFFSET         0x00000050
#define SYSCTL_IMC_OFFSET         0x00000054
#define SYSCTL_MISC_OFFSET        0x00000058
#define SYSCTL_RESC_OFFSET        0x0000005C
#define SYSCTL_PWRTC_OFFSET       0x00000060
#define SYSCTL_NMIC_OFFSET        0x00000064
#define SYSCTL_MOSCCTL_OFFSET     0x0000007C
#define SYSCTL_RSCLKCFG_OFFSET    0x000000B0
#define SYSCTL_MEMTIM0_OFFSET     0x000000C0
#define SYSCTL_ALTCLKCFG_OFFSET   0x00000138
#define SYSCTL_DSCLKCFG_OFFSET    0x00000144
#define SYSCTL_DIVSCLK_OFFSET     0x00000148
#define SYSCTL_SYSPROP_OFFSET     0x0000014C
#define SYSCTL_PIOSCCAL_OFFSET    0x00000150
#define SYSCTL_PIOSCSTAT_OFFSET   0x00000154
#define SYSCTL_PLLFREQ0_OFFSET    0x00000160
#define SYSCTL_PLLFREQ1_OFFSET    0x00000164
#define SYSCTL_PLLSTAT_OFFSET     0x00000168
#define SYSCTL_SLPPWRCFG_OFFSET   0x00000188
#define SYSCTL_DSLPPWRCFG_OFFSET  0x0000018C
#define SYSCTL_NVMSTAT_OFFSET     0x000001A0
#define SYSCTL_LDOSPCTL_OFFSET    0x000001B4
#define SYSCTL_LDOSPCAL_OFFSET    0x000001B8
#define SYSCTL_LDODPCTL_OFFSET    0x000001BC
#define SYSCTL_LDODPCAL_OFFSET    0x000001C0
#define SYSCTL_SDPMST_OFFSET      0x000001CC
#define SYSCTL_RESBEHAVCTL_OFFSET 0x000001D8
#define SYSCTL_HSSR_OFFSET        0x000001F4
#define SYSCTL_USBPDS_OFFSET      0x00000280
#define SYSCTL_USBMPC_OFFSET      0x00000284
#define SYSCTL_EMACPDS_OFFSET     0x00000288
#define SYSCTL_EMACMPC_OFFSET     0x0000028C
#define SYSCTL_CAN0PDS_OFFSET     0x00000298
#define SYSCTL_CAN0MPC_OFFSET     0x0000029C
#define SYSCTL_CAN1PDS_OFFSET     0x000002A0
#define SYSCTL_CAN1MPC_OFFSET     0x000002A4
#define SYSCTL_PPWD_OFFSET        0x00000300
#define SYSCTL_PPTIMER_OFFSET     0x00000304
#define SYSCTL_PPGPIO_OFFSET      0x00000308
#define SYSCTL_PPDMA_OFFSET       0x0000030C
#define SYSCTL_PPEPI_OFFSET       0x00000310
#define SYSCTL_PPHIB_OFFSET       0x00000314
#define SYSCTL_PPUART_OFFSET      0x00000318
#define SYSCTL_PPSSI_OFFSET       0x0000031C
#define SYSCTL_PPI2C_OFFSET       0x00000320
#define SYSCTL_PPUSB_OFFSET       0x00000328
#define SYSCTL_PPEPHY_OFFSET      0x00000330
#define SYSCTL_PPCAN_OFFSET       0x00000334
#define SYSCTL_PPADC_OFFSET       0x00000338
#define SYSCTL_PPACMP_OFFSET      0x0000033C
#define SYSCTL_PPPWM_OFFSET       0x00000340
#define SYSCTL_PPQEI_OFFSET       0x00000344
#define SYSCTL_PPLPC_OFFSET       0x00000348
#define SYSCTL_PPPECI_OFFSET      0x00000350
#define SYSCTL_PPFAN_OFFSET       0x00000354
#define SYSCTL_PPEEPROM_OFFSET    0x00000358
#define SYSCTL_PPWTIMER_OFFSET    0x0000035C
#define SYSCTL_PPRTS_OFFSET       0x00000370
#define SYSCTL_PPCCM_OFFSET       0x00000374
#define SYSCTL_PPLCD_OFFSET       0x00000390
#define SYSCTL_PPOWIRE_OFFSET     0x00000398
#define SYSCTL_PPEMAC_OFFSET      0x0000039C
#define SYSCTL_PPPRB_OFFSET       0x000003A0
#define SYSCTL_PPHIM_OFFSET       0x000003A4
#define SYSCTL_SRWD_OFFSET        0x00000500
#define SYSCTL_SRTIMER_OFFSET     0x00000504
#define SYSCTL_SRGPIO_OFFSET      0x00000508
#define SYSCTL_SRDMA_OFFSET       0x0000050C
#define SYSCTL_SREPI_OFFSET       0x00000510
#define SYSCTL_SRHIB_OFFSET       0x00000514
#define SYSCTL_SRUART_OFFSET      0x00000518
#define SYSCTL_SRSSI_OFFSET       0x0000051C
#define SYSCTL_SRI2C_OFFSET       0x00000520
#define SYSCTL_SRUSB_OFFSET       0x00000528
#define SYSCTL_SREPHY_OFFSET      0x00000530
#define SYSCTL_SRCAN_OFFSET       0x00000534
#define SYSCTL_SRADC_OFFSET       0x00000538
#define SYSCTL_SRACMP_OFFSET      0x0000053C
#define SYSCTL_SRPWM_OFFSET       0x00000540
#define SYSCTL_SRQEI_OFFSET       0x00000544
#define SYSCTL_SREEPROM_OFFSET    0x00000558
#define SYSCTL_SRCCM_OFFSET       0x00000574
#define SYSCTL_SREMAC_OFFSET      0x0000059C
#define SYSCTL_RCGCWD_OFFSET      0x00000600
#define SYSCTL_RCGCTIMER_OFFSET   0x00000604
#define SYSCTL_RCGCGPIO_OFFSET    0x00000608
#define SYSCTL_RCGCDMA_OFFSET     0x0000060C
#define SYSCTL_RCGCEPI_OFFSET     0x00000610
#define SYSCTL_RCGCHIB_OFFSET     0x00000614
#define SYSCTL_RCGCUART_OFFSET    0x00000618
#define SYSCTL_RCGCSSI_OFFSET     0x0000061C
#define SYSCTL_RCGCI2C_OFFSET     0x00000620
#define SYSCTL_RCGCUSB_OFFSET     0x00000628
#define SYSCTL_RCGCEPHY_OFFSET    0x00000630
#define SYSCTL_RCGCCAN_OFFSET     0x00000634
#define SYSCTL_RCGCADC_OFFSET     0x00000638
#define SYSCTL_RCGCACMP_OFFSET    0x0000063C
#define SYSCTL_RCGCPWM_OFFSET     0x00000640
#define SYSCTL_RCGCQEI_OFFSET     0x00000644
#define SYSCTL_RCGCEEPROM_OFFSET  0x00000658
#define SYSCTL_RCGCCCM_OFFSET     0x00000674
#define SYSCTL_RCGCEMAC_OFFSET    0x0000069C
#define SYSCTL_SCGCWD_OFFSET      0x00000700
#define SYSCTL_SCGCTIMER_OFFSET   0x00000704
#define SYSCTL_SCGCGPIO_OFFSET    0x00000708
#define SYSCTL_SCGCDMA_OFFSET     0x0000070C
#define SYSCTL_SCGCEPI_OFFSET     0x00000710
#define SYSCTL_SCGCHIB_OFFSET     0x00000714
#define SYSCTL_SCGCUART_OFFSET    0x00000718
#define SYSCTL_SCGCSSI_OFFSET     0x0000071C
#define SYSCTL_SCGCI2C_OFFSET     0x00000720
#define SYSCTL_SCGCUSB_OFFSET     0x00000728
#define SYSCTL_SCGCEPHY_OFFSET    0x00000730
#define SYSCTL_SCGCCAN_OFFSET     0x00000734
#define SYSCTL_SCGCADC_OFFSET     0x00000738
#define SYSCTL_SCGCACMP_OFFSET    0x0000073C
#define SYSCTL_SCGCPWM_OFFSET     0x00000740
#define SYSCTL_SCGCQEI_OFFSET     0x00000744
#define SYSCTL_SCGCEEPROM_OFFSET  0x00000758
#define SYSCTL_SCGCCCM_OFFSET     0x00000774
#define SYSCTL_SCGCEMAC_OFFSET    0x0000079C
#define SYSCTL_DCGCWD_OFFSET      0x00000800
#define SYSCTL_DCGCTIMER_OFFSET   0x00000804
#define SYSCTL_DCGCGPIO_OFFSET    0x00000808
#define SYSCTL_DCGCDMA_OFFSET     0x0000080C
#define SYSCTL_DCGCEPI_OFFSET     0x00000810
#define SYSCTL_DCGCHIB_OFFSET     0x00000814
#define SYSCTL_DCGCUART_OFFSET    0x00000818
#define SYSCTL_DCGCSSI_OFFSET     0x0000081C
#define SYSCTL_DCGCI2C_OFFSET     0x00000820
#define SYSCTL_DCGCUSB_OFFSET     0x00000828
#define SYSCTL_DCGCEPHY_OFFSET    0x00000830
#define SYSCTL_DCGCCAN_OFFSET     0x00000834
#define SYSCTL_DCGCADC_OFFSET     0x00000838
#define SYSCTL_DCGCACMP_OFFSET    0x0000083C
#define SYSCTL_DCGCPWM_OFFSET     0x00000840
#define SYSCTL_DCGCQEI_OFFSET     0x00000844
#define SYSCTL_DCGCEEPROM_OFFSET  0x00000858
#define SYSCTL_DCGCCCM_OFFSET     0x00000874
#define SYSCTL_DCGCEMAC_OFFSET    0x0000089C
#define SYSCTL_PCWD_OFFSET        0x00000900
#define SYSCTL_PCTIMER_OFFSET     0x00000904
#define SYSCTL_PCGPIO_OFFSET      0x00000908
#define SYSCTL_PCDMA_OFFSET       0x0000090C
#define SYSCTL_PCEPI_OFFSET       0x00000910
#define SYSCTL_PCHIB_OFFSET       0x00000914
#define SYSCTL_PCUART_OFFSET      0x00000918
#define SYSCTL_PCSSI_OFFSET       0x0000091C
#define SYSCTL_PCI2C_OFFSET       0x00000920
#define SYSCTL_PCUSB_OFFSET       0x00000928
#define SYSCTL_PCEPHY_OFFSET      0x00000930
#define SYSCTL_PCCAN_OFFSET       0x00000934
#define SYSCTL_PCADC_OFFSET       0x00000938
#define SYSCTL_PCACMP_OFFSET      0x0000093C
#define SYSCTL_PCPWM_OFFSET       0x00000940
#define SYSCTL_PCQEI_OFFSET       0x00000944
#define SYSCTL_PCEEPROM_OFFSET    0x00000958
#define SYSCTL_PCCCM_OFFSET       0x00000974
#define SYSCTL_PCEMAC_OFFSET      0x0000099C
#define SYSCTL_PRWD_OFFSET        0x00000A00
#define SYSCTL_PRTIMER_OFFSET     0x00000A04
#define SYSCTL_PRGPIO_OFFSET      0x00000A08
#define SYSCTL_PRDMA_OFFSET       0x00000A0C
#define SYSCTL_PREPI_OFFSET       0x00000A10
#define SYSCTL_PRHIB_OFFSET       0x00000A14
#define SYSCTL_PRUART_OFFSET      0x00000A18
#define SYSCTL_PRSSI_OFFSET       0x00000A1C
#define SYSCTL_PRI2C_OFFSET       0x00000A20
#define SYSCTL_PRUSB_OFFSET       0x00000A28
#define SYSCTL_PREPHY_OFFSET      0x00000A30
#define SYSCTL_PRCAN_OFFSET       0x00000A34
#define SYSCTL_PRADC_OFFSET       0x00000A38
#define SYSCTL_PRACMP_OFFSET      0x00000A3C
#define SYSCTL_PRPWM_OFFSET       0x00000A40
#define SYSCTL_PRQEI_OFFSET       0x00000A44
#define SYSCTL_PREEPROM_OFFSET    0x00000A58
#define SYSCTL_PRCCM_OFFSET       0x00000A74
#define SYSCTL_PREMAC_OFFSET      0x00000A9C
#define SYSCTL_UNIQUEID0_OFFSET   0x00000F20
#define SYSCTL_UNIQUEID1_OFFSET   0x00000F24
#define SYSCTL_UNIQUEID2_OFFSET   0x00000F28
#define SYSCTL_UNIQUEID3_OFFSET   0x00000F2C
#define SYSCTL_CCMCGREQ_OFFSET    0x00000204


// Register Defintions
#define SYSCTL_DID0        REGISTER(SYSCTL_BASE + SYSCTL_DID0_OFFSET)
#define SYSCTL_DID1        REGISTER(SYSCTL_BASE + SYSCTL_DID1_OFFSET)
#define SYSCTL_PTBOCTL     REGISTER(SYSCTL_BASE + SYSCTL_PTBOCTL_OFFSET)
#define SYSCTL_RIS         REGISTER(SYSCTL_BASE + SYSCTL_RIS_OFFSET)
#define SYSCTL_IMC         REGISTER(SYSCTL_BASE + SYSCTL_IMC_OFFSET)
#define SYSCTL_MISC        REGISTER(SYSCTL_BASE + SYSCTL_MISC_OFFSET)
#define SYSCTL_RESC        REGISTER(SYSCTL_BASE + SYSCTL_RESC_OFFSET)
#define SYSCTL_PWRTC       REGISTER(SYSCTL_BASE + SYSCTL_PWRTC_OFFSET)
#define SYSCTL_NMIC        REGISTER(SYSCTL_BASE + SYSCTL_NMIC_OFFSET)
#define SYSCTL_MOSCCTL     REGISTER(SYSCTL_BASE + SYSCTL_MOSCCTL_OFFSET)
#define SYSCTL_RSCLKCFG    REGISTER(SYSCTL_BASE + SYSCTL_RSCLKCFG_OFFSET)
#define SYSCTL_MEMTIM0     REGISTER(SYSCTL_BASE + SYSCTL_MEMTIM0_OFFSET)
#define SYSCTL_ALTCLKCFG   REGISTER(SYSCTL_BASE + SYSCTL_ALTCLKCFG_OFFSET)
#define SYSCTL_DSCLKCFG    REGISTER(SYSCTL_BASE + SYSCTL_DSCLKCFG_OFFSET)
#define SYSCTL_DIVSCLK     REGISTER(SYSCTL_BASE + SYSCTL_DIVSCLK_OFFSET)
#define SYSCTL_SYSPROP     REGISTER(SYSCTL_BASE + SYSCTL_SYSPROP_OFFSET)
#define SYSCTL_PIOSCCAL    REGISTER(SYSCTL_BASE + SYSCTL_PIOSCCAL_OFFSET)
#define SYSCTL_PIOSCSTAT   REGISTER(SYSCTL_BASE + SYSCTL_PIOSCSTAT_OFFSET)
#define SYSCTL_PLLFREQ0    REGISTER(SYSCTL_BASE + SYSCTL_PLLFREQ0_OFFSET)
#define SYSCTL_PLLFREQ1    REGISTER(SYSCTL_BASE + SYSCTL_PLLFREQ1_OFFSET)
#define SYSCTL_PLLSTAT     REGISTER(SYSCTL_BASE + SYSCTL_PLLSTAT_OFFSET)
#define SYSCTL_SLPPWRCFG   REGISTER(SYSCTL_BASE + SYSCTL_SLPPWRCFG_OFFSET)
#define SYSCTL_DSLPPWRCFG  REGISTER(SYSCTL_BASE + SYSCTL_DSLPPWRCFG_OFFSET)
#define SYSCTL_NVMSTAT     REGISTER(SYSCTL_BASE + SYSCTL_NVMSTAT_OFFSET)
#define SYSCTL_LDOSPCTL    REGISTER(SYSCTL_BASE + SYSCTL_LDOSPCTL_OFFSET)
#define SYSCTL_LDOSPCAL    REGISTER(SYSCTL_BASE + SYSCTL_LDOSPCAL_OFFSET)
#define SYSCTL_LDODPCTL    REGISTER(SYSCTL_BASE + SYSCTL_LDODPCTL_OFFSET)
#define SYSCTL_LDODPCAL    REGISTER(SYSCTL_BASE + SYSCTL_LDODPCAL_OFFSET)
#define SYSCTL_SDPMST      REGISTER(SYSCTL_BASE + SYSCTL_SDPMST_OFFSET)
#define SYSCTL_RESBEHAVCTL REGISTER(SYSCTL_BASE + SYSCTL_RESBEHAVCTL_OFFSET)
#define SYSCTL_HSSR        REGISTER(SYSCTL_BASE + SYSCTL_HSSR_OFFSET)
#define SYSCTL_USBPDS      REGISTER(SYSCTL_BASE + SYSCTL_USBPDS_OFFSET)
#define SYSCTL_USBMPC      REGISTER(SYSCTL_BASE + SYSCTL_USBMPC_OFFSET)
#define SYSCTL_EMACPDS     REGISTER(SYSCTL_BASE + SYSCTL_EMACPDS_OFFSET)
#define SYSCTL_EMACMPC     REGISTER(SYSCTL_BASE + SYSCTL_EMACMPC_OFFSET)
#define SYSCTL_CAN0PDS     REGISTER(SYSCTL_BASE + SYSCTL_CAN0PDS_OFFSET)
#define SYSCTL_CAN0MPC     REGISTER(SYSCTL_BASE + SYSCTL_CAN0MPC_OFFSET)
#define SYSCTL_CAN1PDS     REGISTER(SYSCTL_BASE + SYSCTL_CAN1PDS_OFFSET)
#define SYSCTL_CAN1MPC     REGISTER(SYSCTL_BASE + SYSCTL_CAN1MPC_OFFSET)
#define SYSCTL_PPWD        REGISTER(SYSCTL_BASE + SYSCTL_PPWD_OFFSET)
#define SYSCTL_PPTIMER     REGISTER(SYSCTL_BASE + SYSCTL_PPTIMER_OFFSET)
#define SYSCTL_PPGPIO      REGISTER(SYSCTL_BASE + SYSCTL_PPGPIO_OFFSET)
#define SYSCTL_PPDMA       REGISTER(SYSCTL_BASE + SYSCTL_PPDMA_OFFSET)
#define SYSCTL_PPEPI       REGISTER(SYSCTL_BASE + SYSCTL_PPEPI_OFFSET)
#define SYSCTL_PPHIB       REGISTER(SYSCTL_BASE + SYSCTL_PPHIB_OFFSET)
#define SYSCTL_PPUART      REGISTER(SYSCTL_BASE + SYSCTL_PPUART_OFFSET)
#define SYSCTL_PPSSI       REGISTER(SYSCTL_BASE + SYSCTL_PPSSI_OFFSET)
#define SYSCTL_PPI2C       REGISTER(SYSCTL_BASE + SYSCTL_PPI2C_OFFSET)
#define SYSCTL_PPUSB       REGISTER(SYSCTL_BASE + SYSCTL_PPUSB_OFFSET)
#define SYSCTL_PPEPHY      REGISTER(SYSCTL_BASE + SYSCTL_PPEPHY_OFFSET)
#define SYSCTL_PPCAN       REGISTER(SYSCTL_BASE + SYSCTL_PPCAN_OFFSET)
#define SYSCTL_PPADC       REGISTER(SYSCTL_BASE + SYSCTL_PPADC_OFFSET)
#define SYSCTL_PPACMP      REGISTER(SYSCTL_BASE + SYSCTL_PPACMP_OFFSET)
#define SYSCTL_PPPWM       REGISTER(SYSCTL_BASE + SYSCTL_PPPWM_OFFSET)
#define SYSCTL_PPQEI       REGISTER(SYSCTL_BASE + SYSCTL_PPQEI_OFFSET)
#define SYSCTL_PPLPC       REGISTER(SYSCTL_BASE + SYSCTL_PPLPC_OFFSET)
#define SYSCTL_PPPECI      REGISTER(SYSCTL_BASE + SYSCTL_PPPECI_OFFSET)
#define SYSCTL_PPFAN       REGISTER(SYSCTL_BASE + SYSCTL_PPFAN_OFFSET)
#define SYSCTL_PPEEPROM    REGISTER(SYSCTL_BASE + SYSCTL_PPEEPROM_OFFSET)
#define SYSCTL_PPWTIMER    REGISTER(SYSCTL_BASE + SYSCTL_PPWTIMER_OFFSET)
#define SYSCTL_PPRTS       REGISTER(SYSCTL_BASE + SYSCTL_PPRTS_OFFSET)
#define SYSCTL_PPCCM       REGISTER(SYSCTL_BASE + SYSCTL_PPCCM_OFFSET)
#define SYSCTL_PPLCD       REGISTER(SYSCTL_BASE + SYSCTL_PPLCD_OFFSET)
#define SYSCTL_PPOWIRE     REGISTER(SYSCTL_BASE + SYSCTL_PPOWIRE_OFFSET)
#define SYSCTL_PPEMAC      REGISTER(SYSCTL_BASE + SYSCTL_PPEMAC_OFFSET)
#define SYSCTL_PPPRB       REGISTER(SYSCTL_BASE + SYSCTL_PPPRB_OFFSET)
#define SYSCTL_PPHIM       REGISTER(SYSCTL_BASE + SYSCTL_PPHIM_OFFSET)
#define SYSCTL_SRWD        REGISTER(SYSCTL_BASE + SYSCTL_SRWD_OFFSET)
#define SYSCTL_SRTIMER     REGISTER(SYSCTL_BASE + SYSCTL_SRTIMER_OFFSET)
#define SYSCTL_SRGPIO      REGISTER(SYSCTL_BASE + SYSCTL_SRGPIO_OFFSET)
#define SYSCTL_SRDMA       REGISTER(SYSCTL_BASE + SYSCTL_SRDMA_OFFSET)
#define SYSCTL_SREPI       REGISTER(SYSCTL_BASE + SYSCTL_SREPI_OFFSET)
#define SYSCTL_SRHIB       REGISTER(SYSCTL_BASE + SYSCTL_SRHIB_OFFSET)
#define SYSCTL_SRUART      REGISTER(SYSCTL_BASE + SYSCTL_SRUART_OFFSET)
#define SYSCTL_SRSSI       REGISTER(SYSCTL_BASE + SYSCTL_SRSSI_OFFSET)
#define SYSCTL_SRI2C       REGISTER(SYSCTL_BASE + SYSCTL_SRI2C_OFFSET)
#define SYSCTL_SRUSB       REGISTER(SYSCTL_BASE + SYSCTL_SRUSB_OFFSET)
#define SYSCTL_SREPHY      REGISTER(SYSCTL_BASE + SYSCTL_SREPHY_OFFSET)
#define SYSCTL_SRCAN       REGISTER(SYSCTL_BASE + SYSCTL_SRCAN_OFFSET)
#define SYSCTL_SRADC       REGISTER(SYSCTL_BASE + SYSCTL_SRADC_OFFSET)
#define SYSCTL_SRACMP      REGISTER(SYSCTL_BASE + SYSCTL_SRACMP_OFFSET)
#define SYSCTL_SRPWM       REGISTER(SYSCTL_BASE + SYSCTL_SRPWM_OFFSET)
#define SYSCTL_SRQEI       REGISTER(SYSCTL_BASE + SYSCTL_SRQEI_OFFSET)
#define SYSCTL_SREEPROM    REGISTER(SYSCTL_BASE + SYSCTL_SREEPROM_OFFSET)
#define SYSCTL_SRCCM       REGISTER(SYSCTL_BASE + SYSCTL_SRCCM_OFFSET)
#define SYSCTL_SREMAC      REGISTER(SYSCTL_BASE + SYSCTL_SREMAC_OFFSET)
#define SYSCTL_RCGCWD      REGISTER(SYSCTL_BASE + SYSCTL_RCGCWD_OFFSET)
#define SYSCTL_RCGCTIMER   REGISTER(SYSCTL_BASE + SYSCTL_RCGCTIMER_OFFSET)
#define SYSCTL_RCGCGPIO    REGISTER(SYSCTL_BASE + SYSCTL_RCGCGPIO_OFFSET)
#define SYSCTL_RCGCDMA     REGISTER(SYSCTL_BASE + SYSCTL_RCGCDMA_OFFSET)
#define SYSCTL_RCGCEPI     REGISTER(SYSCTL_BASE + SYSCTL_RCGCEPI_OFFSET)
#define SYSCTL_RCGCHIB     REGISTER(SYSCTL_BASE + SYSCTL_RCGCHIB_OFFSET)
#define SYSCTL_RCGCUART    REGISTER(SYSCTL_BASE + SYSCTL_RCGCUART_OFFSET)
#define SYSCTL_RCGCSSI     REGISTER(SYSCTL_BASE + SYSCTL_RCGCSSI_OFFSET)
#define SYSCTL_RCGCI2C     REGISTER(SYSCTL_BASE + SYSCTL_RCGCI2C_OFFSET)
#define SYSCTL_RCGCUSB     REGISTER(SYSCTL_BASE + SYSCTL_RCGCUSB_OFFSET)
#define SYSCTL_RCGCEPHY    REGISTER(SYSCTL_BASE + SYSCTL_RCGCEPHY_OFFSET)
#define SYSCTL_RCGCCAN     REGISTER(SYSCTL_BASE + SYSCTL_RCGCCAN_OFFSET)
#define SYSCTL_RCGCADC     REGISTER(SYSCTL_BASE + SYSCTL_RCGCADC_OFFSET)
#define SYSCTL_RCGCACMP    REGISTER(SYSCTL_BASE + SYSCTL_RCGCACMP_OFFSET)
#define SYSCTL_RCGCPWM     REGISTER(SYSCTL_BASE + SYSCTL_RCGCPWM_OFFSET)
#define SYSCTL_RCGCQEI     REGISTER(SYSCTL_BASE + SYSCTL_RCGCQEI_OFFSET)
#define SYSCTL_RCGCEEPROM  REGISTER(SYSCTL_BASE + SYSCTL_RCGCEEPROM_OFFSET)
#define SYSCTL_RCGCCCM     REGISTER(SYSCTL_BASE + SYSCTL_RCGCCCM_OFFSET)
#define SYSCTL_RCGCEMAC    REGISTER(SYSCTL_BASE + SYSCTL_RCGCEMAC_OFFSET)
#define SYSCTL_SCGCWD      REGISTER(SYSCTL_BASE + SYSCTL_SCGCWD_OFFSET)
#define SYSCTL_SCGCTIMER   REGISTER(SYSCTL_BASE + SYSCTL_SCGCTIMER_OFFSET)
#define SYSCTL_SCGCGPIO    REGISTER(SYSCTL_BASE + SYSCTL_SCGCGPIO_OFFSET)
#define SYSCTL_SCGCDMA     REGISTER(SYSCTL_BASE + SYSCTL_SCGCDMA_OFFSET)
#define SYSCTL_SCGCEPI     REGISTER(SYSCTL_BASE + SYSCTL_SCGCEPI_OFFSET)
#define SYSCTL_SCGCHIB     REGISTER(SYSCTL_BASE + SYSCTL_SCGCHIB_OFFSET)
#define SYSCTL_SCGCUART    REGISTER(SYSCTL_BASE + SYSCTL_SCGCUART_OFFSET)
#define SYSCTL_SCGCSSI     REGISTER(SYSCTL_BASE + SYSCTL_SCGCSSI_OFFSET)
#define SYSCTL_SCGCI2C     REGISTER(SYSCTL_BASE + SYSCTL_SCGCI2C_OFFSET)
#define SYSCTL_SCGCUSB     REGISTER(SYSCTL_BASE + SYSCTL_SCGCUSB_OFFSET)
#define SYSCTL_SCGCEPHY    REGISTER(SYSCTL_BASE + SYSCTL_SCGCEPHY_OFFSET)
#define SYSCTL_SCGCCAN     REGISTER(SYSCTL_BASE + SYSCTL_SCGCCAN_OFFSET)
#define SYSCTL_SCGCADC     REGISTER(SYSCTL_BASE + SYSCTL_SCGCADC_OFFSET)
#define SYSCTL_SCGCACMP    REGISTER(SYSCTL_BASE + SYSCTL_SCGCACMP_OFFSET)
#define SYSCTL_SCGCPWM     REGISTER(SYSCTL_BASE + SYSCTL_SCGCPWM_OFFSET)
#define SYSCTL_SCGCQEI     REGISTER(SYSCTL_BASE + SYSCTL_SCGCQEI_OFFSET)
#define SYSCTL_SCGCEEPROM  REGISTER(SYSCTL_BASE + SYSCTL_SCGCEEPROM_OFFSET)
#define SYSCTL_SCGCCCM     REGISTER(SYSCTL_BASE + SYSCTL_SCGCCCM_OFFSET)
#define SYSCTL_SCGCEMAC    REGISTER(SYSCTL_BASE + SYSCTL_SCGCEMAC_OFFSET)
#define SYSCTL_DCGCWD      REGISTER(SYSCTL_BASE + SYSCTL_DCGCWD_OFFSET)
#define SYSCTL_DCGCTIMER   REGISTER(SYSCTL_BASE + SYSCTL_DCGCTIMER_OFFSET)
#define SYSCTL_DCGCGPIO    REGISTER(SYSCTL_BASE + SYSCTL_DCGCGPIO_OFFSET)
#define SYSCTL_DCGCDMA     REGISTER(SYSCTL_BASE + SYSCTL_DCGCDMA_OFFSET)
#define SYSCTL_DCGCEPI     REGISTER(SYSCTL_BASE + SYSCTL_DCGCEPI_OFFSET)
#define SYSCTL_DCGCHIB     REGISTER(SYSCTL_BASE + SYSCTL_DCGCHIB_OFFSET)
#define SYSCTL_DCGCUART    REGISTER(SYSCTL_BASE + SYSCTL_DCGCUART_OFFSET)
#define SYSCTL_DCGCSSI     REGISTER(SYSCTL_BASE + SYSCTL_DCGCSSI_OFFSET)
#define SYSCTL_DCGCI2C     REGISTER(SYSCTL_BASE + SYSCTL_DCGCI2C_OFFSET)
#define SYSCTL_DCGCUSB     REGISTER(SYSCTL_BASE + SYSCTL_DCGCUSB_OFFSET)
#define SYSCTL_DCGCEPHY    REGISTER(SYSCTL_BASE + SYSCTL_DCGCEPHY_OFFSET)
#define SYSCTL_DCGCCAN     REGISTER(SYSCTL_BASE + SYSCTL_DCGCCAN_OFFSET)
#define SYSCTL_DCGCADC     REGISTER(SYSCTL_BASE + SYSCTL_DCGCADC_OFFSET)
#define SYSCTL_DCGCACMP    REGISTER(SYSCTL_BASE + SYSCTL_DCGCACMP_OFFSET)
#define SYSCTL_DCGCPWM     REGISTER(SYSCTL_BASE + SYSCTL_DCGCPWM_OFFSET)
#define SYSCTL_DCGCQEI     REGISTER(SYSCTL_BASE + SYSCTL_DCGCQEI_OFFSET)
#define SYSCTL_DCGCEEPROM  REGISTER(SYSCTL_BASE + SYSCTL_DCGCEEPROM_OFFSET)
#define SYSCTL_DCGCCCM     REGISTER(SYSCTL_BASE + SYSCTL_DCGCCCM_OFFSET)
#define SYSCTL_DCGCEMAC    REGISTER(SYSCTL_BASE + SYSCTL_DCGCEMAC_OFFSET)
#define SYSCTL_PCWD        REGISTER(SYSCTL_BASE + SYSCTL_PCWD_OFFSET)
#define SYSCTL_PCTIMER     REGISTER(SYSCTL_BASE + SYSCTL_PCTIMER_OFFSET)
#define SYSCTL_PCGPIO      REGISTER(SYSCTL_BASE + SYSCTL_PCGPIO_OFFSET)
#define SYSCTL_PCDMA       REGISTER(SYSCTL_BASE + SYSCTL_PCDMA_OFFSET)
#define SYSCTL_PCEPI       REGISTER(SYSCTL_BASE + SYSCTL_PCEPI_OFFSET)
#define SYSCTL_PCHIB       REGISTER(SYSCTL_BASE + SYSCTL_PCHIB_OFFSET)
#define SYSCTL_PCUART      REGISTER(SYSCTL_BASE + SYSCTL_PCUART_OFFSET)
#define SYSCTL_PCSSI       REGISTER(SYSCTL_BASE + SYSCTL_PCSSI_OFFSET)
#define SYSCTL_PCI2C       REGISTER(SYSCTL_BASE + SYSCTL_PCI2C_OFFSET)
#define SYSCTL_PCUSB       REGISTER(SYSCTL_BASE + SYSCTL_PCUSB_OFFSET)
#define SYSCTL_PCEPHY      REGISTER(SYSCTL_BASE + SYSCTL_PCEPHY_OFFSET)
#define SYSCTL_PCCAN       REGISTER(SYSCTL_BASE + SYSCTL_PCCAN_OFFSET)
#define SYSCTL_PCADC       REGISTER(SYSCTL_BASE + SYSCTL_PCADC_OFFSET)
#define SYSCTL_PCACMP      REGISTER(SYSCTL_BASE + SYSCTL_PCACMP_OFFSET)
#define SYSCTL_PCPWM       REGISTER(SYSCTL_BASE + SYSCTL_PCPWM_OFFSET)
#define SYSCTL_PCQEI       REGISTER(SYSCTL_BASE + SYSCTL_PCQEI_OFFSET)
#define SYSCTL_PCEEPROM    REGISTER(SYSCTL_BASE + SYSCTL_PCEEPROM_OFFSET)
#define SYSCTL_PCCCM       REGISTER(SYSCTL_BASE + SYSCTL_PCCCM_OFFSET)
#define SYSCTL_PCEMAC      REGISTER(SYSCTL_BASE + SYSCTL_PCEMAC_OFFSET)
#define SYSCTL_PRWD        REGISTER(SYSCTL_BASE + SYSCTL_PRWD_OFFSET)
#define SYSCTL_PRTIMER     REGISTER(SYSCTL_BASE + SYSCTL_PRTIMER_OFFSET)
#define SYSCTL_PRGPIO      REGISTER(SYSCTL_BASE + SYSCTL_PRGPIO_OFFSET)
#define SYSCTL_PRDMA       REGISTER(SYSCTL_BASE + SYSCTL_PRDMA_OFFSET)
#define SYSCTL_PREPI       REGISTER(SYSCTL_BASE + SYSCTL_PREPI_OFFSET)
#define SYSCTL_PRHIB       REGISTER(SYSCTL_BASE + SYSCTL_PRHIB_OFFSET)
#define SYSCTL_PRUART      REGISTER(SYSCTL_BASE + SYSCTL_PRUART_OFFSET)
#define SYSCTL_PRSSI       REGISTER(SYSCTL_BASE + SYSCTL_PRSSI_OFFSET)
#define SYSCTL_PRI2C       REGISTER(SYSCTL_BASE + SYSCTL_PRI2C_OFFSET)
#define SYSCTL_PRUSB       REGISTER(SYSCTL_BASE + SYSCTL_PRUSB_OFFSET)
#define SYSCTL_PREPHY      REGISTER(SYSCTL_BASE + SYSCTL_PREPHY_OFFSET)
#define SYSCTL_PRCAN       REGISTER(SYSCTL_BASE + SYSCTL_PRCAN_OFFSET)
#define SYSCTL_PRADC       REGISTER(SYSCTL_BASE + SYSCTL_PRADC_OFFSET)
#define SYSCTL_PRACMP      REGISTER(SYSCTL_BASE + SYSCTL_PRACMP_OFFSET)
#define SYSCTL_PRPWM       REGISTER(SYSCTL_BASE + SYSCTL_PRPWM_OFFSET)
#define SYSCTL_PRQEI       REGISTER(SYSCTL_BASE + SYSCTL_PRQEI_OFFSET)
#define SYSCTL_PREEPROM    REGISTER(SYSCTL_BASE + SYSCTL_PREEPROM_OFFSET)
#define SYSCTL_PRCCM       REGISTER(SYSCTL_BASE + SYSCTL_PRCCM_OFFSET)
#define SYSCTL_PREMAC      REGISTER(SYSCTL_BASE + SYSCTL_PREMAC_OFFSET)
#define SYSCTL_UNIQUEID0   REGISTER(SYSCTL_BASE + SYSCTL_UNIQUEID0_OFFSET)
#define SYSCTL_UNIQUEID1   REGISTER(SYSCTL_BASE + SYSCTL_UNIQUEID1_OFFSET)
#define SYSCTL_UNIQUEID2   REGISTER(SYSCTL_BASE + SYSCTL_UNIQUEID2_OFFSET)
#define SYSCTL_UNIQUEID3   REGISTER(SYSCTL_BASE + SYSCTL_UNIQUEID3_OFFSET)
#define SYSCTL_CCMCGREQ    REGISTER(SYSCTL_BASE + SYSCTL_CCMCGREQ_OFFSET)

