#pragma once

#include "registers/register_helpers.h"

// Timer Register Offsets
#define TIMER_CFG_OFFSET      0x00000000
#define TIMER_TAMR_OFFSET     0x00000004
#define TIMER_TBMR_OFFSET     0x00000008
#define TIMER_CTL_OFFSET      0x0000000C
#define TIMER_SYNC_OFFSET     0x00000010
#define TIMER_IMR_OFFSET      0x00000018
#define TIMER_RIS_OFFSET      0x0000001C
#define TIMER_MIS_OFFSET      0x00000020
#define TIMER_ICR_OFFSET      0x00000024
#define TIMER_TAILR_OFFSET    0x00000028
#define TIMER_TBILR_OFFSET    0x0000002C
#define TIMER_TAMATCHR_OFFSET 0x00000030
#define TIMER_TBMATCHR_OFFSET 0x00000034
#define TIMER_TAPR_OFFSET     0x00000038
#define TIMER_TBPR_OFFSET     0x0000003C
#define TIMER_TAPMR_OFFSET    0x00000040
#define TIMER_TBPMR_OFFSET    0x00000044
#define TIMER_TAR_OFFSET      0x00000048
#define TIMER_TBR_OFFSET      0x0000004C
#define TIMER_TAV_OFFSET      0x00000050
#define TIMER_TBV_OFFSET      0x00000054
#define TIMER_RTCPD_OFFSET    0x00000058
#define TIMER_TAPS_OFFSET     0x0000005C
#define TIMER_TBPS_OFFSET     0x00000060
#define TIMER_DMAEV_OFFSET    0x0000006C
#define TIMER_ADCEV_OFFSET    0x00000070
#define TIMER_PP_OFFSET       0x00000FC0
#define TIMER_CC_OFFSET       0x00000FC8


// Timer Definitions
// Timer 0
#define TIMER_0_BASE 0x40030000
#define TIMER_0_CFG      REGISTER(TIMER_0_BASE + TIMER_CFG_OFFSET)
#define TIMER_0_TAMR     REGISTER(TIMER_0_BASE + TIMER_TAMR_OFFSET)
#define TIMER_0_TBMR     REGISTER(TIMER_0_BASE + TIMER_TBMR_OFFSET)
#define TIMER_0_CTL      REGISTER(TIMER_0_BASE + TIMER_CTL_OFFSET)
#define TIMER_0_SYNC     REGISTER(TIMER_0_BASE + TIMER_SYNC_OFFSET)
#define TIMER_0_IMR      REGISTER(TIMER_0_BASE + TIMER_IMR_OFFSET)
#define TIMER_0_RIS      REGISTER(TIMER_0_BASE + TIMER_RIS_OFFSET)
#define TIMER_0_MIS      REGISTER(TIMER_0_BASE + TIMER_MIS_OFFSET)
#define TIMER_0_ICR      REGISTER(TIMER_0_BASE + TIMER_ICR_OFFSET)
#define TIMER_0_TAILR    REGISTER(TIMER_0_BASE + TIMER_TAILR_OFFSET)
#define TIMER_0_TBILR    REGISTER(TIMER_0_BASE + TIMER_TBILR_OFFSET)
#define TIMER_0_TAMATCHR REGISTER(TIMER_0_BASE + TIMER_TAMATCHR_OFFSET)
#define TIMER_0_TBMATCHR REGISTER(TIMER_0_BASE + TIMER_TBMATCHR_OFFSET)
#define TIMER_0_TAPR     REGISTER(TIMER_0_BASE + TIMER_TAPR_OFFSET)
#define TIMER_0_TBPR     REGISTER(TIMER_0_BASE + TIMER_TBPR_OFFSET)
#define TIMER_0_TAPMR    REGISTER(TIMER_0_BASE + TIMER_TAPMR_OFFSET)
#define TIMER_0_TBPMR    REGISTER(TIMER_0_BASE + TIMER_TBPMR_OFFSET)
#define TIMER_0_TAR      REGISTER(TIMER_0_BASE + TIMER_TAR_OFFSET)
#define TIMER_0_TBR      REGISTER(TIMER_0_BASE + TIMER_TBR_OFFSET)
#define TIMER_0_TAV      REGISTER(TIMER_0_BASE + TIMER_TAV_OFFSET)
#define TIMER_0_TBV      REGISTER(TIMER_0_BASE + TIMER_TBV_OFFSET)
#define TIMER_0_RTCPD    REGISTER(TIMER_0_BASE + TIMER_RTCPD_OFFSET)
#define TIMER_0_TAPS     REGISTER(TIMER_0_BASE + TIMER_TAPS_OFFSET)
#define TIMER_0_TBPS     REGISTER(TIMER_0_BASE + TIMER_TBPS_OFFSET)
#define TIMER_0_DMAEV    REGISTER(TIMER_0_BASE + TIMER_DMAEV_OFFSET)
#define TIMER_0_ADCEV    REGISTER(TIMER_0_BASE + TIMER_ADCEV_OFFSET)
#define TIMER_0_PP       REGISTER(TIMER_0_BASE + TIMER_PP_OFFSET)
#define TIMER_0_CC       REGISTER(TIMER_0_BASE + TIMER_CC_OFFSET)

// Timer 1
#define TIMER_1_BASE 0x40031000
#define TIMER_1_CFG      REGISTER(TIMER_1_BASE + TIMER_CFG_OFFSET)
#define TIMER_1_TAMR     REGISTER(TIMER_1_BASE + TIMER_TAMR_OFFSET)
#define TIMER_1_TBMR     REGISTER(TIMER_1_BASE + TIMER_TBMR_OFFSET)
#define TIMER_1_CTL      REGISTER(TIMER_1_BASE + TIMER_CTL_OFFSET)
#define TIMER_1_SYNC     REGISTER(TIMER_1_BASE + TIMER_SYNC_OFFSET)
#define TIMER_1_IMR      REGISTER(TIMER_1_BASE + TIMER_IMR_OFFSET)
#define TIMER_1_RIS      REGISTER(TIMER_1_BASE + TIMER_RIS_OFFSET)
#define TIMER_1_MIS      REGISTER(TIMER_1_BASE + TIMER_MIS_OFFSET)
#define TIMER_1_ICR      REGISTER(TIMER_1_BASE + TIMER_ICR_OFFSET)
#define TIMER_1_TAILR    REGISTER(TIMER_1_BASE + TIMER_TAILR_OFFSET)
#define TIMER_1_TBILR    REGISTER(TIMER_1_BASE + TIMER_TBILR_OFFSET)
#define TIMER_1_TAMATCHR REGISTER(TIMER_1_BASE + TIMER_TAMATCHR_OFFSET)
#define TIMER_1_TBMATCHR REGISTER(TIMER_1_BASE + TIMER_TBMATCHR_OFFSET)
#define TIMER_1_TAPR     REGISTER(TIMER_1_BASE + TIMER_TAPR_OFFSET)
#define TIMER_1_TBPR     REGISTER(TIMER_1_BASE + TIMER_TBPR_OFFSET)
#define TIMER_1_TAPMR    REGISTER(TIMER_1_BASE + TIMER_TAPMR_OFFSET)
#define TIMER_1_TBPMR    REGISTER(TIMER_1_BASE + TIMER_TBPMR_OFFSET)
#define TIMER_1_TAR      REGISTER(TIMER_1_BASE + TIMER_TAR_OFFSET)
#define TIMER_1_TBR      REGISTER(TIMER_1_BASE + TIMER_TBR_OFFSET)
#define TIMER_1_TAV      REGISTER(TIMER_1_BASE + TIMER_TAV_OFFSET)
#define TIMER_1_TBV      REGISTER(TIMER_1_BASE + TIMER_TBV_OFFSET)
#define TIMER_1_RTCPD    REGISTER(TIMER_1_BASE + TIMER_RTCPD_OFFSET)
#define TIMER_1_TAPS     REGISTER(TIMER_1_BASE + TIMER_TAPS_OFFSET)
#define TIMER_1_TBPS     REGISTER(TIMER_1_BASE + TIMER_TBPS_OFFSET)
#define TIMER_1_DMAEV    REGISTER(TIMER_1_BASE + TIMER_DMAEV_OFFSET)
#define TIMER_1_ADCEV    REGISTER(TIMER_1_BASE + TIMER_ADCEV_OFFSET)
#define TIMER_1_PP       REGISTER(TIMER_1_BASE + TIMER_PP_OFFSET)
#define TIMER_1_CC       REGISTER(TIMER_1_BASE + TIMER_CC_OFFSET)

// Timer 2
#define TIMER_2_BASE 0x40032000
#define TIMER_2_CFG      REGISTER(TIMER_2_BASE + TIMER_CFG_OFFSET)
#define TIMER_2_TAMR     REGISTER(TIMER_2_BASE + TIMER_TAMR_OFFSET)
#define TIMER_2_TBMR     REGISTER(TIMER_2_BASE + TIMER_TBMR_OFFSET)
#define TIMER_2_CTL      REGISTER(TIMER_2_BASE + TIMER_CTL_OFFSET)
#define TIMER_2_SYNC     REGISTER(TIMER_2_BASE + TIMER_SYNC_OFFSET)
#define TIMER_2_IMR      REGISTER(TIMER_2_BASE + TIMER_IMR_OFFSET)
#define TIMER_2_RIS      REGISTER(TIMER_2_BASE + TIMER_RIS_OFFSET)
#define TIMER_2_MIS      REGISTER(TIMER_2_BASE + TIMER_MIS_OFFSET)
#define TIMER_2_ICR      REGISTER(TIMER_2_BASE + TIMER_ICR_OFFSET)
#define TIMER_2_TAILR    REGISTER(TIMER_2_BASE + TIMER_TAILR_OFFSET)
#define TIMER_2_TBILR    REGISTER(TIMER_2_BASE + TIMER_TBILR_OFFSET)
#define TIMER_2_TAMATCHR REGISTER(TIMER_2_BASE + TIMER_TAMATCHR_OFFSET)
#define TIMER_2_TBMATCHR REGISTER(TIMER_2_BASE + TIMER_TBMATCHR_OFFSET)
#define TIMER_2_TAPR     REGISTER(TIMER_2_BASE + TIMER_TAPR_OFFSET)
#define TIMER_2_TBPR     REGISTER(TIMER_2_BASE + TIMER_TBPR_OFFSET)
#define TIMER_2_TAPMR    REGISTER(TIMER_2_BASE + TIMER_TAPMR_OFFSET)
#define TIMER_2_TBPMR    REGISTER(TIMER_2_BASE + TIMER_TBPMR_OFFSET)
#define TIMER_2_TAR      REGISTER(TIMER_2_BASE + TIMER_TAR_OFFSET)
#define TIMER_2_TBR      REGISTER(TIMER_2_BASE + TIMER_TBR_OFFSET)
#define TIMER_2_TAV      REGISTER(TIMER_2_BASE + TIMER_TAV_OFFSET)
#define TIMER_2_TBV      REGISTER(TIMER_2_BASE + TIMER_TBV_OFFSET)
#define TIMER_2_RTCPD    REGISTER(TIMER_2_BASE + TIMER_RTCPD_OFFSET)
#define TIMER_2_TAPS     REGISTER(TIMER_2_BASE + TIMER_TAPS_OFFSET)
#define TIMER_2_TBPS     REGISTER(TIMER_2_BASE + TIMER_TBPS_OFFSET)
#define TIMER_2_DMAEV    REGISTER(TIMER_2_BASE + TIMER_DMAEV_OFFSET)
#define TIMER_2_ADCEV    REGISTER(TIMER_2_BASE + TIMER_ADCEV_OFFSET)
#define TIMER_2_PP       REGISTER(TIMER_2_BASE + TIMER_PP_OFFSET)
#define TIMER_2_CC       REGISTER(TIMER_2_BASE + TIMER_CC_OFFSET)

// Timer 3
#define TIMER_3_BASE 0x40033000
#define TIMER_3_CFG      REGISTER(TIMER_3_BASE + TIMER_CFG_OFFSET)
#define TIMER_3_TAMR     REGISTER(TIMER_3_BASE + TIMER_TAMR_OFFSET)
#define TIMER_3_TBMR     REGISTER(TIMER_3_BASE + TIMER_TBMR_OFFSET)
#define TIMER_3_CTL      REGISTER(TIMER_3_BASE + TIMER_CTL_OFFSET)
#define TIMER_3_SYNC     REGISTER(TIMER_3_BASE + TIMER_SYNC_OFFSET)
#define TIMER_3_IMR      REGISTER(TIMER_3_BASE + TIMER_IMR_OFFSET)
#define TIMER_3_RIS      REGISTER(TIMER_3_BASE + TIMER_RIS_OFFSET)
#define TIMER_3_MIS      REGISTER(TIMER_3_BASE + TIMER_MIS_OFFSET)
#define TIMER_3_ICR      REGISTER(TIMER_3_BASE + TIMER_ICR_OFFSET)
#define TIMER_3_TAILR    REGISTER(TIMER_3_BASE + TIMER_TAILR_OFFSET)
#define TIMER_3_TBILR    REGISTER(TIMER_3_BASE + TIMER_TBILR_OFFSET)
#define TIMER_3_TAMATCHR REGISTER(TIMER_3_BASE + TIMER_TAMATCHR_OFFSET)
#define TIMER_3_TBMATCHR REGISTER(TIMER_3_BASE + TIMER_TBMATCHR_OFFSET)
#define TIMER_3_TAPR     REGISTER(TIMER_3_BASE + TIMER_TAPR_OFFSET)
#define TIMER_3_TBPR     REGISTER(TIMER_3_BASE + TIMER_TBPR_OFFSET)
#define TIMER_3_TAPMR    REGISTER(TIMER_3_BASE + TIMER_TAPMR_OFFSET)
#define TIMER_3_TBPMR    REGISTER(TIMER_3_BASE + TIMER_TBPMR_OFFSET)
#define TIMER_3_TAR      REGISTER(TIMER_3_BASE + TIMER_TAR_OFFSET)
#define TIMER_3_TBR      REGISTER(TIMER_3_BASE + TIMER_TBR_OFFSET)
#define TIMER_3_TAV      REGISTER(TIMER_3_BASE + TIMER_TAV_OFFSET)
#define TIMER_3_TBV      REGISTER(TIMER_3_BASE + TIMER_TBV_OFFSET)
#define TIMER_3_RTCPD    REGISTER(TIMER_3_BASE + TIMER_RTCPD_OFFSET)
#define TIMER_3_TAPS     REGISTER(TIMER_3_BASE + TIMER_TAPS_OFFSET)
#define TIMER_3_TBPS     REGISTER(TIMER_3_BASE + TIMER_TBPS_OFFSET)
#define TIMER_3_DMAEV    REGISTER(TIMER_3_BASE + TIMER_DMAEV_OFFSET)
#define TIMER_3_ADCEV    REGISTER(TIMER_3_BASE + TIMER_ADCEV_OFFSET)
#define TIMER_3_PP       REGISTER(TIMER_3_BASE + TIMER_PP_OFFSET)
#define TIMER_3_CC       REGISTER(TIMER_3_BASE + TIMER_CC_OFFSET)

// Timer 4
#define TIMER_4_BASE 0x40034000
#define TIMER_4_CFG      REGISTER(TIMER_4_BASE + TIMER_CFG_OFFSET)
#define TIMER_4_TAMR     REGISTER(TIMER_4_BASE + TIMER_TAMR_OFFSET)
#define TIMER_4_TBMR     REGISTER(TIMER_4_BASE + TIMER_TBMR_OFFSET)
#define TIMER_4_CTL      REGISTER(TIMER_4_BASE + TIMER_CTL_OFFSET)
#define TIMER_4_SYNC     REGISTER(TIMER_4_BASE + TIMER_SYNC_OFFSET)
#define TIMER_4_IMR      REGISTER(TIMER_4_BASE + TIMER_IMR_OFFSET)
#define TIMER_4_RIS      REGISTER(TIMER_4_BASE + TIMER_RIS_OFFSET)
#define TIMER_4_MIS      REGISTER(TIMER_4_BASE + TIMER_MIS_OFFSET)
#define TIMER_4_ICR      REGISTER(TIMER_4_BASE + TIMER_ICR_OFFSET)
#define TIMER_4_TAILR    REGISTER(TIMER_4_BASE + TIMER_TAILR_OFFSET)
#define TIMER_4_TBILR    REGISTER(TIMER_4_BASE + TIMER_TBILR_OFFSET)
#define TIMER_4_TAMATCHR REGISTER(TIMER_4_BASE + TIMER_TAMATCHR_OFFSET)
#define TIMER_4_TBMATCHR REGISTER(TIMER_4_BASE + TIMER_TBMATCHR_OFFSET)
#define TIMER_4_TAPR     REGISTER(TIMER_4_BASE + TIMER_TAPR_OFFSET)
#define TIMER_4_TBPR     REGISTER(TIMER_4_BASE + TIMER_TBPR_OFFSET)
#define TIMER_4_TAPMR    REGISTER(TIMER_4_BASE + TIMER_TAPMR_OFFSET)
#define TIMER_4_TBPMR    REGISTER(TIMER_4_BASE + TIMER_TBPMR_OFFSET)
#define TIMER_4_TAR      REGISTER(TIMER_4_BASE + TIMER_TAR_OFFSET)
#define TIMER_4_TBR      REGISTER(TIMER_4_BASE + TIMER_TBR_OFFSET)
#define TIMER_4_TAV      REGISTER(TIMER_4_BASE + TIMER_TAV_OFFSET)
#define TIMER_4_TBV      REGISTER(TIMER_4_BASE + TIMER_TBV_OFFSET)
#define TIMER_4_RTCPD    REGISTER(TIMER_4_BASE + TIMER_RTCPD_OFFSET)
#define TIMER_4_TAPS     REGISTER(TIMER_4_BASE + TIMER_TAPS_OFFSET)
#define TIMER_4_TBPS     REGISTER(TIMER_4_BASE + TIMER_TBPS_OFFSET)
#define TIMER_4_DMAEV    REGISTER(TIMER_4_BASE + TIMER_DMAEV_OFFSET)
#define TIMER_4_ADCEV    REGISTER(TIMER_4_BASE + TIMER_ADCEV_OFFSET)
#define TIMER_4_PP       REGISTER(TIMER_4_BASE + TIMER_PP_OFFSET)
#define TIMER_4_CC       REGISTER(TIMER_4_BASE + TIMER_CC_OFFSET)

// Timer 5
#define TIMER_5_BASE 0x40035000
#define TIMER_5_CFG      REGISTER(TIMER_1_BASE + TIMER_CFG_OFFSET)
#define TIMER_5_TAMR     REGISTER(TIMER_1_BASE + TIMER_TAMR_OFFSET)
#define TIMER_5_TBMR     REGISTER(TIMER_1_BASE + TIMER_TBMR_OFFSET)
#define TIMER_5_CTL      REGISTER(TIMER_1_BASE + TIMER_CTL_OFFSET)
#define TIMER_5_SYNC     REGISTER(TIMER_1_BASE + TIMER_SYNC_OFFSET)
#define TIMER_5_IMR      REGISTER(TIMER_1_BASE + TIMER_IMR_OFFSET)
#define TIMER_5_RIS      REGISTER(TIMER_1_BASE + TIMER_RIS_OFFSET)
#define TIMER_5_MIS      REGISTER(TIMER_1_BASE + TIMER_MIS_OFFSET)
#define TIMER_5_ICR      REGISTER(TIMER_1_BASE + TIMER_ICR_OFFSET)
#define TIMER_5_TAILR    REGISTER(TIMER_1_BASE + TIMER_TAILR_OFFSET)
#define TIMER_5_TBILR    REGISTER(TIMER_1_BASE + TIMER_TBILR_OFFSET)
#define TIMER_5_TAMATCHR REGISTER(TIMER_1_BASE + TIMER_TAMATCHR_OFFSET)
#define TIMER_5_TBMATCHR REGISTER(TIMER_1_BASE + TIMER_TBMATCHR_OFFSET)
#define TIMER_5_TAPR     REGISTER(TIMER_1_BASE + TIMER_TAPR_OFFSET)
#define TIMER_5_TBPR     REGISTER(TIMER_1_BASE + TIMER_TBPR_OFFSET)
#define TIMER_5_TAPMR    REGISTER(TIMER_1_BASE + TIMER_TAPMR_OFFSET)
#define TIMER_5_TBPMR    REGISTER(TIMER_1_BASE + TIMER_TBPMR_OFFSET)
#define TIMER_5_TAR      REGISTER(TIMER_1_BASE + TIMER_TAR_OFFSET)
#define TIMER_5_TBR      REGISTER(TIMER_1_BASE + TIMER_TBR_OFFSET)
#define TIMER_5_TAV      REGISTER(TIMER_1_BASE + TIMER_TAV_OFFSET)
#define TIMER_5_TBV      REGISTER(TIMER_1_BASE + TIMER_TBV_OFFSET)
#define TIMER_5_RTCPD    REGISTER(TIMER_1_BASE + TIMER_RTCPD_OFFSET)
#define TIMER_5_TAPS     REGISTER(TIMER_1_BASE + TIMER_TAPS_OFFSET)
#define TIMER_5_TBPS     REGISTER(TIMER_1_BASE + TIMER_TBPS_OFFSET)
#define TIMER_5_DMAEV    REGISTER(TIMER_1_BASE + TIMER_DMAEV_OFFSET)
#define TIMER_5_ADCEV    REGISTER(TIMER_1_BASE + TIMER_ADCEV_OFFSET)
#define TIMER_5_PP       REGISTER(TIMER_1_BASE + TIMER_PP_OFFSET)
#define TIMER_5_CC       REGISTER(TIMER_1_BASE + TIMER_CC_OFFSET)

// Timer 6
#define TIMER_6_BASE 0x400E0000
#define TIMER_6_CFG      REGISTER(TIMER_6_BASE + TIMER_CFG_OFFSET)
#define TIMER_6_TAMR     REGISTER(TIMER_6_BASE + TIMER_TAMR_OFFSET)
#define TIMER_6_TBMR     REGISTER(TIMER_6_BASE + TIMER_TBMR_OFFSET)
#define TIMER_6_CTL      REGISTER(TIMER_6_BASE + TIMER_CTL_OFFSET)
#define TIMER_6_SYNC     REGISTER(TIMER_6_BASE + TIMER_SYNC_OFFSET)
#define TIMER_6_IMR      REGISTER(TIMER_6_BASE + TIMER_IMR_OFFSET)
#define TIMER_6_RIS      REGISTER(TIMER_6_BASE + TIMER_RIS_OFFSET)
#define TIMER_6_MIS      REGISTER(TIMER_6_BASE + TIMER_MIS_OFFSET)
#define TIMER_6_ICR      REGISTER(TIMER_6_BASE + TIMER_ICR_OFFSET)
#define TIMER_6_TAILR    REGISTER(TIMER_6_BASE + TIMER_TAILR_OFFSET)
#define TIMER_6_TBILR    REGISTER(TIMER_6_BASE + TIMER_TBILR_OFFSET)
#define TIMER_6_TAMATCHR REGISTER(TIMER_6_BASE + TIMER_TAMATCHR_OFFSET)
#define TIMER_6_TBMATCHR REGISTER(TIMER_6_BASE + TIMER_TBMATCHR_OFFSET)
#define TIMER_6_TAPR     REGISTER(TIMER_6_BASE + TIMER_TAPR_OFFSET)
#define TIMER_6_TBPR     REGISTER(TIMER_6_BASE + TIMER_TBPR_OFFSET)
#define TIMER_6_TAPMR    REGISTER(TIMER_6_BASE + TIMER_TAPMR_OFFSET)
#define TIMER_6_TBPMR    REGISTER(TIMER_6_BASE + TIMER_TBPMR_OFFSET)
#define TIMER_6_TAR      REGISTER(TIMER_6_BASE + TIMER_TAR_OFFSET)
#define TIMER_6_TBR      REGISTER(TIMER_6_BASE + TIMER_TBR_OFFSET)
#define TIMER_6_TAV      REGISTER(TIMER_6_BASE + TIMER_TAV_OFFSET)
#define TIMER_6_TBV      REGISTER(TIMER_6_BASE + TIMER_TBV_OFFSET)
#define TIMER_6_RTCPD    REGISTER(TIMER_6_BASE + TIMER_RTCPD_OFFSET)
#define TIMER_6_TAPS     REGISTER(TIMER_6_BASE + TIMER_TAPS_OFFSET)
#define TIMER_6_TBPS     REGISTER(TIMER_6_BASE + TIMER_TBPS_OFFSET)
#define TIMER_6_DMAEV    REGISTER(TIMER_6_BASE + TIMER_DMAEV_OFFSET)
#define TIMER_6_ADCEV    REGISTER(TIMER_6_BASE + TIMER_ADCEV_OFFSET)
#define TIMER_6_PP       REGISTER(TIMER_6_BASE + TIMER_PP_OFFSET)
#define TIMER_6_CC       REGISTER(TIMER_6_BASE + TIMER_CC_OFFSET)

// Timer 7
#define TIMER_7_BASE 0x400E1000
#define TIMER_7_CFG      REGISTER(TIMER_7_BASE + TIMER_CFG_OFFSET)
#define TIMER_7_TAMR     REGISTER(TIMER_7_BASE + TIMER_TAMR_OFFSET)
#define TIMER_7_TBMR     REGISTER(TIMER_7_BASE + TIMER_TBMR_OFFSET)
#define TIMER_7_CTL      REGISTER(TIMER_7_BASE + TIMER_CTL_OFFSET)
#define TIMER_7_SYNC     REGISTER(TIMER_7_BASE + TIMER_SYNC_OFFSET)
#define TIMER_7_IMR      REGISTER(TIMER_7_BASE + TIMER_IMR_OFFSET)
#define TIMER_7_RIS      REGISTER(TIMER_7_BASE + TIMER_RIS_OFFSET)
#define TIMER_7_MIS      REGISTER(TIMER_7_BASE + TIMER_MIS_OFFSET)
#define TIMER_7_ICR      REGISTER(TIMER_7_BASE + TIMER_ICR_OFFSET)
#define TIMER_7_TAILR    REGISTER(TIMER_7_BASE + TIMER_TAILR_OFFSET)
#define TIMER_7_TBILR    REGISTER(TIMER_7_BASE + TIMER_TBILR_OFFSET)
#define TIMER_7_TAMATCHR REGISTER(TIMER_7_BASE + TIMER_TAMATCHR_OFFSET)
#define TIMER_7_TBMATCHR REGISTER(TIMER_7_BASE + TIMER_TBMATCHR_OFFSET)
#define TIMER_7_TAPR     REGISTER(TIMER_7_BASE + TIMER_TAPR_OFFSET)
#define TIMER_7_TBPR     REGISTER(TIMER_7_BASE + TIMER_TBPR_OFFSET)
#define TIMER_7_TAPMR    REGISTER(TIMER_7_BASE + TIMER_TAPMR_OFFSET)
#define TIMER_7_TBPMR    REGISTER(TIMER_7_BASE + TIMER_TBPMR_OFFSET)
#define TIMER_7_TAR      REGISTER(TIMER_7_BASE + TIMER_TAR_OFFSET)
#define TIMER_7_TBR      REGISTER(TIMER_7_BASE + TIMER_TBR_OFFSET)
#define TIMER_7_TAV      REGISTER(TIMER_7_BASE + TIMER_TAV_OFFSET)
#define TIMER_7_TBV      REGISTER(TIMER_7_BASE + TIMER_TBV_OFFSET)
#define TIMER_7_RTCPD    REGISTER(TIMER_7_BASE + TIMER_RTCPD_OFFSET)
#define TIMER_7_TAPS     REGISTER(TIMER_7_BASE + TIMER_TAPS_OFFSET)
#define TIMER_7_TBPS     REGISTER(TIMER_7_BASE + TIMER_TBPS_OFFSET)
#define TIMER_7_DMAEV    REGISTER(TIMER_7_BASE + TIMER_DMAEV_OFFSET)
#define TIMER_7_ADCEV    REGISTER(TIMER_7_BASE + TIMER_ADCEV_OFFSET)
#define TIMER_7_PP       REGISTER(TIMER_7_BASE + TIMER_PP_OFFSET)
#define TIMER_7_CC       REGISTER(TIMER_7_BASE + TIMER_CC_OFFSET)

