#pragma once

#include "registers/register_helpers.h"

// UART Register Offsets
#define UART_DR_OFFSET          0x00000000
#define UART_RSR_UARTECR_OFFSET 0x00000004
#define UART_FR_OFFSET          0x00000018
#define UART_ILPR_OFFSET        0x00000020
#define UART_IBRD_OFFSET        0x00000024
#define UART_FBRD_OFFSET        0x00000028
#define UART_LCRH_OFFSET        0x0000002C
#define UART_CTL_OFFSET         0x00000030
#define UART_IFLS_OFFSET        0x00000034
#define UART_IM_OFFSET          0x00000038
#define UART_RIS_OFFSET         0x0000003C
#define UART_MIS_OFFSET         0x00000040
#define UART_ICR_OFFSET         0x00000044
#define UART_DMACTL_OFFSET      0x00000048
#define UART_9BITADDR_OFFSET    0x000000A4
#define UART_9BITAMASK_OFFSET   0x000000A8
#define UART_PP_OFFSET          0x00000FC0
#define UART_CC_OFFSET          0x00000FC8
#define UART_PeriphID4_OFFSET   0x00000FD0
#define UART_PeriphID5_OFFSET   0x00000FD4
#define UART_PeriphID6_OFFSET   0x00000FD8
#define UART_PeriphID7_OFFSET   0x00000FDC
#define UART_PeriphID0_OFFSET   0x00000FE0
#define UART_PeriphID1_OFFSET   0x00000FE4
#define UART_PeriphID2_OFFSET   0x00000FE8
#define UART_PeriphID3_OFFSET   0x00000FEC
#define UART_PCellID0_OFFSET    0x00000FF0
#define UART_PCellID1_OFFSET    0x00000FF4
#define UART_PCellID2_OFFSET    0x00000FF8
#define UART_PCellID3_OFFSET    0x00000FFC

// UART Register Definitions
// UART 0
#define UART0_BASE 0x4000C000
#define UART0_DR          REGISTER(UART0_BASE + UART_DR_OFFSET)
#define UART0_RSR_UARTECR REGISTER(UART0_BASE + UART_RSR_UARTECR_OFFSET)
#define UART0_FR          REGISTER(UART0_BASE + UART_FR_OFFSET)
#define UART0_ILPR        REGISTER(UART0_BASE + UART_ILPR_OFFSET)
#define UART0_IBRD        REGISTER(UART0_BASE + UART_IBRD_OFFSET)
#define UART0_FBRD        REGISTER(UART0_BASE + UART_FBRD_OFFSET)
#define UART0_LCRH        REGISTER(UART0_BASE + UART_LCRH_OFFSET)
#define UART0_CTL         REGISTER(UART0_BASE + UART_CTL_OFFSET)
#define UART0_IFLS        REGISTER(UART0_BASE + UART_IFLS_OFFSET)
#define UART0_IM          REGISTER(UART0_BASE + UART_IM_OFFSET)
#define UART0_RIS         REGISTER(UART0_BASE + UART_RIS_OFFSET)
#define UART0_MIS         REGISTER(UART0_BASE + UART_MIS_OFFSET)
#define UART0_ICR         REGISTER(UART0_BASE + UART_ICR_OFFSET)
#define UART0_DMACTL      REGISTER(UART0_BASE + UART_DMACTL_OFFSET)
#define UART0_9BITADDR    REGISTER(UART0_BASE + UART_9BITADDR_OFFSET)
#define UART0_9BITAMASK   REGISTER(UART0_BASE + UART_9BITAMASK_OFFSET)
#define UART0_PP          REGISTER(UART0_BASE + UART_PP_OFFSET)
#define UART0_CC          REGISTER(UART0_BASE + UART_CC_OFFSET)
#define UART0_PeriphID4   REGISTER(UART0_BASE + UART_PeriphID4_OFFSET)
#define UART0_PeriphID5   REGISTER(UART0_BASE + UART_PeriphID5_OFFSET)
#define UART0_PeriphID6   REGISTER(UART0_BASE + UART_PeriphID6_OFFSET)
#define UART0_PeriphID7   REGISTER(UART0_BASE + UART_PeriphID7_OFFSET)
#define UART0_PeriphID0   REGISTER(UART0_BASE + UART_PeriphID0_OFFSET)
#define UART0_PeriphID1   REGISTER(UART0_BASE + UART_PeriphID1_OFFSET)
#define UART0_PeriphID2   REGISTER(UART0_BASE + UART_PeriphID2_OFFSET)
#define UART0_PeriphID3   REGISTER(UART0_BASE + UART_PeriphID3_OFFSET)
#define UART0_PCellID0    REGISTER(UART0_BASE + UART_PCellID0_OFFSET)
#define UART0_PCellID1    REGISTER(UART0_BASE + UART_PCellID1_OFFSET)
#define UART0_PCellID2    REGISTER(UART0_BASE + UART_PCellID2_OFFSET)
#define UART0_PCellID3    REGISTER(UART0_BASE + UART_PCellID3_OFFSET)

// UART 1
#define UART1_BASE 0x4000D000
#define UART1_DR          REGISTER(UART1_BASE + UART_DR_OFFSET)
#define UART1_RSR_UARTECR REGISTER(UART1_BASE + UART_RSR_UARTECR_OFFSET)
#define UART1_FR          REGISTER(UART1_BASE + UART_FR_OFFSET)
#define UART1_ILPR        REGISTER(UART1_BASE + UART_ILPR_OFFSET)
#define UART1_IBRD        REGISTER(UART1_BASE + UART_IBRD_OFFSET)
#define UART1_FBRD        REGISTER(UART1_BASE + UART_FBRD_OFFSET)
#define UART1_LCRH        REGISTER(UART1_BASE + UART_LCRH_OFFSET)
#define UART1_CTL         REGISTER(UART1_BASE + UART_CTL_OFFSET)
#define UART1_IFLS        REGISTER(UART1_BASE + UART_IFLS_OFFSET)
#define UART1_IM          REGISTER(UART1_BASE + UART_IM_OFFSET)
#define UART1_RIS         REGISTER(UART1_BASE + UART_RIS_OFFSET)
#define UART1_MIS         REGISTER(UART1_BASE + UART_MIS_OFFSET)
#define UART1_ICR         REGISTER(UART1_BASE + UART_ICR_OFFSET)
#define UART1_DMACTL      REGISTER(UART1_BASE + UART_DMACTL_OFFSET)
#define UART1_9BITADDR    REGISTER(UART1_BASE + UART_9BITADDR_OFFSET)
#define UART1_9BITAMASK   REGISTER(UART1_BASE + UART_9BITAMASK_OFFSET)
#define UART1_PP          REGISTER(UART1_BASE + UART_PP_OFFSET)
#define UART1_CC          REGISTER(UART1_BASE + UART_CC_OFFSET)
#define UART1_PeriphID4   REGISTER(UART1_BASE + UART_PeriphID4_OFFSET)
#define UART1_PeriphID5   REGISTER(UART1_BASE + UART_PeriphID5_OFFSET)
#define UART1_PeriphID6   REGISTER(UART1_BASE + UART_PeriphID6_OFFSET)
#define UART1_PeriphID7   REGISTER(UART1_BASE + UART_PeriphID7_OFFSET)
#define UART1_PeriphID0   REGISTER(UART1_BASE + UART_PeriphID0_OFFSET)
#define UART1_PeriphID1   REGISTER(UART1_BASE + UART_PeriphID1_OFFSET)
#define UART1_PeriphID2   REGISTER(UART1_BASE + UART_PeriphID2_OFFSET)
#define UART1_PeriphID3   REGISTER(UART1_BASE + UART_PeriphID3_OFFSET)
#define UART1_PCellID0    REGISTER(UART1_BASE + UART_PCellID0_OFFSET)
#define UART1_PCellID1    REGISTER(UART1_BASE + UART_PCellID1_OFFSET)
#define UART1_PCellID2    REGISTER(UART1_BASE + UART_PCellID2_OFFSET)
#define UART1_PCellID3    REGISTER(UART1_BASE + UART_PCellID3_OFFSET)

// UART 2
#define UART2_BASE 0x4000E000
#define UART2_DR          REGISTER(UART2_BASE + UART_DR_OFFSET)
#define UART2_RSR_UARTECR REGISTER(UART2_BASE + UART_RSR_UARTECR_OFFSET)
#define UART2_FR          REGISTER(UART2_BASE + UART_FR_OFFSET)
#define UART2_ILPR        REGISTER(UART2_BASE + UART_ILPR_OFFSET)
#define UART2_IBRD        REGISTER(UART2_BASE + UART_IBRD_OFFSET)
#define UART2_FBRD        REGISTER(UART2_BASE + UART_FBRD_OFFSET)
#define UART2_LCRH        REGISTER(UART2_BASE + UART_LCRH_OFFSET)
#define UART2_CTL         REGISTER(UART2_BASE + UART_CTL_OFFSET)
#define UART2_IFLS        REGISTER(UART2_BASE + UART_IFLS_OFFSET)
#define UART2_IM          REGISTER(UART2_BASE + UART_IM_OFFSET)
#define UART2_RIS         REGISTER(UART2_BASE + UART_RIS_OFFSET)
#define UART2_MIS         REGISTER(UART2_BASE + UART_MIS_OFFSET)
#define UART2_ICR         REGISTER(UART2_BASE + UART_ICR_OFFSET)
#define UART2_DMACTL      REGISTER(UART2_BASE + UART_DMACTL_OFFSET)
#define UART2_9BITADDR    REGISTER(UART2_BASE + UART_9BITADDR_OFFSET)
#define UART2_9BITAMASK   REGISTER(UART2_BASE + UART_9BITAMASK_OFFSET)
#define UART2_PP          REGISTER(UART2_BASE + UART_PP_OFFSET)
#define UART2_CC          REGISTER(UART2_BASE + UART_CC_OFFSET)
#define UART2_PeriphID4   REGISTER(UART2_BASE + UART_PeriphID4_OFFSET)
#define UART2_PeriphID5   REGISTER(UART2_BASE + UART_PeriphID5_OFFSET)
#define UART2_PeriphID6   REGISTER(UART2_BASE + UART_PeriphID6_OFFSET)
#define UART2_PeriphID7   REGISTER(UART2_BASE + UART_PeriphID7_OFFSET)
#define UART2_PeriphID0   REGISTER(UART2_BASE + UART_PeriphID0_OFFSET)
#define UART2_PeriphID1   REGISTER(UART2_BASE + UART_PeriphID1_OFFSET)
#define UART2_PeriphID2   REGISTER(UART2_BASE + UART_PeriphID2_OFFSET)
#define UART2_PeriphID3   REGISTER(UART2_BASE + UART_PeriphID3_OFFSET)
#define UART2_PCellID0    REGISTER(UART2_BASE + UART_PCellID0_OFFSET)
#define UART2_PCellID1    REGISTER(UART2_BASE + UART_PCellID1_OFFSET)
#define UART2_PCellID2    REGISTER(UART2_BASE + UART_PCellID2_OFFSET)
#define UART2_PCellID3    REGISTER(UART2_BASE + UART_PCellID3_OFFSET)

// UART 3
#define UART3_BASE 0x4000F000
#define UART3_DR          REGISTER(UART3_BASE + UART_DR_OFFSET)
#define UART3_RSR_UARTECR REGISTER(UART3_BASE + UART_RSR_UARTECR_OFFSET)
#define UART3_FR          REGISTER(UART3_BASE + UART_FR_OFFSET)
#define UART3_ILPR        REGISTER(UART3_BASE + UART_ILPR_OFFSET)
#define UART3_IBRD        REGISTER(UART3_BASE + UART_IBRD_OFFSET)
#define UART3_FBRD        REGISTER(UART3_BASE + UART_FBRD_OFFSET)
#define UART3_LCRH        REGISTER(UART3_BASE + UART_LCRH_OFFSET)
#define UART3_CTL         REGISTER(UART3_BASE + UART_CTL_OFFSET)
#define UART3_IFLS        REGISTER(UART3_BASE + UART_IFLS_OFFSET)
#define UART3_IM          REGISTER(UART3_BASE + UART_IM_OFFSET)
#define UART3_RIS         REGISTER(UART3_BASE + UART_RIS_OFFSET)
#define UART3_MIS         REGISTER(UART3_BASE + UART_MIS_OFFSET)
#define UART3_ICR         REGISTER(UART3_BASE + UART_ICR_OFFSET)
#define UART3_DMACTL      REGISTER(UART3_BASE + UART_DMACTL_OFFSET)
#define UART3_9BITADDR    REGISTER(UART3_BASE + UART_9BITADDR_OFFSET)
#define UART3_9BITAMASK   REGISTER(UART3_BASE + UART_9BITAMASK_OFFSET)
#define UART3_PP          REGISTER(UART3_BASE + UART_PP_OFFSET)
#define UART3_CC          REGISTER(UART3_BASE + UART_CC_OFFSET)
#define UART3_PeriphID4   REGISTER(UART3_BASE + UART_PeriphID4_OFFSET)
#define UART3_PeriphID5   REGISTER(UART3_BASE + UART_PeriphID5_OFFSET)
#define UART3_PeriphID6   REGISTER(UART3_BASE + UART_PeriphID6_OFFSET)
#define UART3_PeriphID7   REGISTER(UART3_BASE + UART_PeriphID7_OFFSET)
#define UART3_PeriphID0   REGISTER(UART3_BASE + UART_PeriphID0_OFFSET)
#define UART3_PeriphID1   REGISTER(UART3_BASE + UART_PeriphID1_OFFSET)
#define UART3_PeriphID2   REGISTER(UART3_BASE + UART_PeriphID2_OFFSET)
#define UART3_PeriphID3   REGISTER(UART3_BASE + UART_PeriphID3_OFFSET)
#define UART3_PCellID0    REGISTER(UART3_BASE + UART_PCellID0_OFFSET)
#define UART3_PCellID1    REGISTER(UART3_BASE + UART_PCellID1_OFFSET)
#define UART3_PCellID2    REGISTER(UART3_BASE + UART_PCellID2_OFFSET)
#define UART3_PCellID3    REGISTER(UART3_BASE + UART_PCellID3_OFFSET)

// UART 4
#define UART4_BASE 0x40010000
#define UART4_DR          REGISTER(UART4_BASE + UART_DR_OFFSET)
#define UART4_RSR_UARTECR REGISTER(UART4_BASE + UART_RSR_UARTECR_OFFSET)
#define UART4_FR          REGISTER(UART4_BASE + UART_FR_OFFSET)
#define UART4_ILPR        REGISTER(UART4_BASE + UART_ILPR_OFFSET)
#define UART4_IBRD        REGISTER(UART4_BASE + UART_IBRD_OFFSET)
#define UART4_FBRD        REGISTER(UART4_BASE + UART_FBRD_OFFSET)
#define UART4_LCRH        REGISTER(UART4_BASE + UART_LCRH_OFFSET)
#define UART4_CTL         REGISTER(UART4_BASE + UART_CTL_OFFSET)
#define UART4_IFLS        REGISTER(UART4_BASE + UART_IFLS_OFFSET)
#define UART4_IM          REGISTER(UART4_BASE + UART_IM_OFFSET)
#define UART4_RIS         REGISTER(UART4_BASE + UART_RIS_OFFSET)
#define UART4_MIS         REGISTER(UART4_BASE + UART_MIS_OFFSET)
#define UART4_ICR         REGISTER(UART4_BASE + UART_ICR_OFFSET)
#define UART4_DMACTL      REGISTER(UART4_BASE + UART_DMACTL_OFFSET)
#define UART4_9BITADDR    REGISTER(UART4_BASE + UART_9BITADDR_OFFSET)
#define UART4_9BITAMASK   REGISTER(UART4_BASE + UART_9BITAMASK_OFFSET)
#define UART4_PP          REGISTER(UART4_BASE + UART_PP_OFFSET)
#define UART4_CC          REGISTER(UART4_BASE + UART_CC_OFFSET)
#define UART4_PeriphID4   REGISTER(UART4_BASE + UART_PeriphID4_OFFSET)
#define UART4_PeriphID5   REGISTER(UART4_BASE + UART_PeriphID5_OFFSET)
#define UART4_PeriphID6   REGISTER(UART4_BASE + UART_PeriphID6_OFFSET)
#define UART4_PeriphID7   REGISTER(UART4_BASE + UART_PeriphID7_OFFSET)
#define UART4_PeriphID0   REGISTER(UART4_BASE + UART_PeriphID0_OFFSET)
#define UART4_PeriphID1   REGISTER(UART4_BASE + UART_PeriphID1_OFFSET)
#define UART4_PeriphID2   REGISTER(UART4_BASE + UART_PeriphID2_OFFSET)
#define UART4_PeriphID3   REGISTER(UART4_BASE + UART_PeriphID3_OFFSET)
#define UART4_PCellID0    REGISTER(UART4_BASE + UART_PCellID0_OFFSET)
#define UART4_PCellID1    REGISTER(UART4_BASE + UART_PCellID1_OFFSET)
#define UART4_PCellID2    REGISTER(UART4_BASE + UART_PCellID2_OFFSET)
#define UART4_PCellID3    REGISTER(UART4_BASE + UART_PCellID3_OFFSET)

// UART 5
#define UART5_BASE 0x40011000
#define UART5_DR          REGISTER(UART5_BASE + UART_DR_OFFSET)
#define UART5_RSR_UARTECR REGISTER(UART5_BASE + UART_RSR_UARTECR_OFFSET)
#define UART5_FR          REGISTER(UART5_BASE + UART_FR_OFFSET)
#define UART5_ILPR        REGISTER(UART5_BASE + UART_ILPR_OFFSET)
#define UART5_IBRD        REGISTER(UART5_BASE + UART_IBRD_OFFSET)
#define UART5_FBRD        REGISTER(UART5_BASE + UART_FBRD_OFFSET)
#define UART5_LCRH        REGISTER(UART5_BASE + UART_LCRH_OFFSET)
#define UART5_CTL         REGISTER(UART5_BASE + UART_CTL_OFFSET)
#define UART5_IFLS        REGISTER(UART5_BASE + UART_IFLS_OFFSET)
#define UART5_IM          REGISTER(UART5_BASE + UART_IM_OFFSET)
#define UART5_RIS         REGISTER(UART5_BASE + UART_RIS_OFFSET)
#define UART5_MIS         REGISTER(UART5_BASE + UART_MIS_OFFSET)
#define UART5_ICR         REGISTER(UART5_BASE + UART_ICR_OFFSET)
#define UART5_DMACTL      REGISTER(UART5_BASE + UART_DMACTL_OFFSET)
#define UART5_9BITADDR    REGISTER(UART5_BASE + UART_9BITADDR_OFFSET)
#define UART5_9BITAMASK   REGISTER(UART5_BASE + UART_9BITAMASK_OFFSET)
#define UART5_PP          REGISTER(UART5_BASE + UART_PP_OFFSET)
#define UART5_CC          REGISTER(UART5_BASE + UART_CC_OFFSET)
#define UART5_PeriphID4   REGISTER(UART5_BASE + UART_PeriphID4_OFFSET)
#define UART5_PeriphID5   REGISTER(UART5_BASE + UART_PeriphID5_OFFSET)
#define UART5_PeriphID6   REGISTER(UART5_BASE + UART_PeriphID6_OFFSET)
#define UART5_PeriphID7   REGISTER(UART5_BASE + UART_PeriphID7_OFFSET)
#define UART5_PeriphID0   REGISTER(UART5_BASE + UART_PeriphID0_OFFSET)
#define UART5_PeriphID1   REGISTER(UART5_BASE + UART_PeriphID1_OFFSET)
#define UART5_PeriphID2   REGISTER(UART5_BASE + UART_PeriphID2_OFFSET)
#define UART5_PeriphID3   REGISTER(UART5_BASE + UART_PeriphID3_OFFSET)
#define UART5_PCellID0    REGISTER(UART5_BASE + UART_PCellID0_OFFSET)
#define UART5_PCellID1    REGISTER(UART5_BASE + UART_PCellID1_OFFSET)
#define UART5_PCellID2    REGISTER(UART5_BASE + UART_PCellID2_OFFSET)
#define UART5_PCellID3    REGISTER(UART5_BASE + UART_PCellID3_OFFSET)

// UART 6
#define UART6_BASE 0x40012000
#define UART6_DR          REGISTER(UART6_BASE + UART_DR_OFFSET)
#define UART6_RSR_UARTECR REGISTER(UART6_BASE + UART_RSR_UARTECR_OFFSET)
#define UART6_FR          REGISTER(UART6_BASE + UART_FR_OFFSET)
#define UART6_ILPR        REGISTER(UART6_BASE + UART_ILPR_OFFSET)
#define UART6_IBRD        REGISTER(UART6_BASE + UART_IBRD_OFFSET)
#define UART6_FBRD        REGISTER(UART6_BASE + UART_FBRD_OFFSET)
#define UART6_LCRH        REGISTER(UART6_BASE + UART_LCRH_OFFSET)
#define UART6_CTL         REGISTER(UART6_BASE + UART_CTL_OFFSET)
#define UART6_IFLS        REGISTER(UART6_BASE + UART_IFLS_OFFSET)
#define UART6_IM          REGISTER(UART6_BASE + UART_IM_OFFSET)
#define UART6_RIS         REGISTER(UART6_BASE + UART_RIS_OFFSET)
#define UART6_MIS         REGISTER(UART6_BASE + UART_MIS_OFFSET)
#define UART6_ICR         REGISTER(UART6_BASE + UART_ICR_OFFSET)
#define UART6_DMACTL      REGISTER(UART6_BASE + UART_DMACTL_OFFSET)
#define UART6_9BITADDR    REGISTER(UART6_BASE + UART_9BITADDR_OFFSET)
#define UART6_9BITAMASK   REGISTER(UART6_BASE + UART_9BITAMASK_OFFSET)
#define UART6_PP          REGISTER(UART6_BASE + UART_PP_OFFSET)
#define UART6_CC          REGISTER(UART6_BASE + UART_CC_OFFSET)
#define UART6_PeriphID4   REGISTER(UART6_BASE + UART_PeriphID4_OFFSET)
#define UART6_PeriphID5   REGISTER(UART6_BASE + UART_PeriphID5_OFFSET)
#define UART6_PeriphID6   REGISTER(UART6_BASE + UART_PeriphID6_OFFSET)
#define UART6_PeriphID7   REGISTER(UART6_BASE + UART_PeriphID7_OFFSET)
#define UART6_PeriphID0   REGISTER(UART6_BASE + UART_PeriphID0_OFFSET)
#define UART6_PeriphID1   REGISTER(UART6_BASE + UART_PeriphID1_OFFSET)
#define UART6_PeriphID2   REGISTER(UART6_BASE + UART_PeriphID2_OFFSET)
#define UART6_PeriphID3   REGISTER(UART6_BASE + UART_PeriphID3_OFFSET)
#define UART6_PCellID0    REGISTER(UART6_BASE + UART_PCellID0_OFFSET)
#define UART6_PCellID1    REGISTER(UART6_BASE + UART_PCellID1_OFFSET)
#define UART6_PCellID2    REGISTER(UART6_BASE + UART_PCellID2_OFFSET)
#define UART6_PCellID3    REGISTER(UART6_BASE + UART_PCellID3_OFFSET)

// UART 7
#define UART7_BASE 0x40013000
#define UART7_DR          REGISTER(UART7_BASE + UART_DR_OFFSET)
#define UART7_RSR_UARTECR REGISTER(UART7_BASE + UART_RSR_UARTECR_OFFSET)
#define UART7_FR          REGISTER(UART7_BASE + UART_FR_OFFSET)
#define UART7_ILPR        REGISTER(UART7_BASE + UART_ILPR_OFFSET)
#define UART7_IBRD        REGISTER(UART7_BASE + UART_IBRD_OFFSET)
#define UART7_FBRD        REGISTER(UART7_BASE + UART_FBRD_OFFSET)
#define UART7_LCRH        REGISTER(UART7_BASE + UART_LCRH_OFFSET)
#define UART7_CTL         REGISTER(UART7_BASE + UART_CTL_OFFSET)
#define UART7_IFLS        REGISTER(UART7_BASE + UART_IFLS_OFFSET)
#define UART7_IM          REGISTER(UART7_BASE + UART_IM_OFFSET)
#define UART7_RIS         REGISTER(UART7_BASE + UART_RIS_OFFSET)
#define UART7_MIS         REGISTER(UART7_BASE + UART_MIS_OFFSET)
#define UART7_ICR         REGISTER(UART7_BASE + UART_ICR_OFFSET)
#define UART7_DMACTL      REGISTER(UART7_BASE + UART_DMACTL_OFFSET)
#define UART7_9BITADDR    REGISTER(UART7_BASE + UART_9BITADDR_OFFSET)
#define UART7_9BITAMASK   REGISTER(UART7_BASE + UART_9BITAMASK_OFFSET)
#define UART7_PP          REGISTER(UART7_BASE + UART_PP_OFFSET)
#define UART7_CC          REGISTER(UART7_BASE + UART_CC_OFFSET)
#define UART7_PeriphID4   REGISTER(UART7_BASE + UART_PeriphID4_OFFSET)
#define UART7_PeriphID5   REGISTER(UART7_BASE + UART_PeriphID5_OFFSET)
#define UART7_PeriphID6   REGISTER(UART7_BASE + UART_PeriphID6_OFFSET)
#define UART7_PeriphID7   REGISTER(UART7_BASE + UART_PeriphID7_OFFSET)
#define UART7_PeriphID0   REGISTER(UART7_BASE + UART_PeriphID0_OFFSET)
#define UART7_PeriphID1   REGISTER(UART7_BASE + UART_PeriphID1_OFFSET)
#define UART7_PeriphID2   REGISTER(UART7_BASE + UART_PeriphID2_OFFSET)
#define UART7_PeriphID3   REGISTER(UART7_BASE + UART_PeriphID3_OFFSET)
#define UART7_PCellID0    REGISTER(UART7_BASE + UART_PCellID0_OFFSET)
#define UART7_PCellID1    REGISTER(UART7_BASE + UART_PCellID1_OFFSET)
#define UART7_PCellID2    REGISTER(UART7_BASE + UART_PCellID2_OFFSET)
#define UART7_PCellID3    REGISTER(UART7_BASE + UART_PCellID3_OFFSET)

